### ISSUE TITLE
Facing a problem in Webhook

### ISSUE THREAD

**Issue by rohit-githubAccount** [stripe/stripe-node#1006]
I am using `app.use(express.json({ limit: '4mb' }));  app.use(express.urlencoded({ limit: '4mb', extended: true }));` middleware. And as a result I am getting `Webhook signature mismatch` error and all other APIs in my application are heavily dependent on the above stated middlewares. In the official document it is stated to use ` bodyParser.raw({type: 'application/json'})`. 
Please suggest any workaround for this ASAP.

**Comment by remi-stripe** [comment]
@rohit-githubAccount Thanks for reaching out. I'd recommend reading through this thread https://github.com/stripe/stripe-node/issues/341 which contains a lot of solutions. It's hard to give you the right one as it depends a lot on your current setup but it should unblock you.

Otherwise, I'd recommend reaching out to our support team for help since it's more a code question and not an issue with the library itself. You can contact them here: https://support.stripe.com/contact

**Comment by rohit-githubAccount** [comment]
Thank you for response. It helped.
