### ISSUE TITLE
display_items empty when retrieving sessions with line_items populated

### ISSUE THREAD

**Issue by MaximeAubanel** [stripe/stripe-node#1010]
I might be missing something but I've been reading the docs since a while but cannot find an answer.

"stripe": "^7.14.0"
node: v14.11.0
api: 2020-08-27

I'm creating a session like that:

```typescript
    const session = await stripe.checkout.sessions.create({
      payment_intent_data: {
        shipping: {
          address: {
            line1: checkoutData.user.address,
            city: checkoutData.user.city,
            country: checkoutData.user.country,
            postal_code: checkoutData.user.postalCode
          },
          name: checkoutData.user.firstname + " " + checkoutData.user.lastname,
        }
      },
      customer_email: checkoutData.user.email,
      payment_method_types: ['card'],
      line_items: checkoutLineItem,
      success_url: url + "/checkout/success/{CHECKOUT_SESSION_ID}",
      cancel_url: url + "/checkout/cancel",
    });
```

`checkoutLineItem` is filled. And when redirect to Stripe's checkout I see my items and data.

I validate the payment using the fake API.

Then I'm redirected to my success page and try to retrieve some info. And especially the items just bought.

However when retrieving the session:

```
const session = await stripe.checkout.sessions.retrieve(session_id)
console.log(session.display_items)
```

`session.display_items` is undefined. How come ? Did I miss something ?

Also, why `line_items` ? What does that mean ? Why this term ?

**Comment by paulasjes-stripe** [comment]
The issues page for this repo is meant for problems with the actual library rather than generic API problems. In the future please reach out to Stripe support directly if you're having issues: https://support.stripe.com/contact

To unblock you however, in API version `2020-08-27` `display_items` was dropped in favor of `line_items`: https://stripe.com/docs/upgrades#2020-08-27.

To understand how `line_items` work you can refer to the API reference: https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-line_items

**Comment by MaximeAubanel** [comment]
@paulasjes-stripe Thanks for your reply but I thought it was an issue related to the library missing some features from the API.

I found the solution to have "line_items" populated:

```typescript
stripe.checkout.sessions.retrieve(session_id, { expand: ["line_items"] })
```
