### ISSUE TITLE
invoices.retrieveUpcoming return type incorrect

### ISSUE THREAD

**Issue by WillSquire** [stripe/stripe-node#1013]
`invoices.retrieveUpcoming` returns `Stripe.Invoice`, but the upcoming invoice doesn't return an `id`. `id` should either be optional or this should be a seperate type.

**Comment by richardm-stripe** [comment]
Hi @WillSquire, sorry for the slow response here.

We experimented with adding a separate type for "UpcomingInvoice", but unfortunately this is a little bit unwieldy. We don't want to change the type of id to optional, either, because in most cases id is not optional, and that would cause a lot of users to have to do an extra type refinement. I think the right thing to do would be to use the "Omit" utility type in the return value of the method (https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys), but unfortunately it will take a little bit of work to add the ability to express this in our code generation infrastructure. I'm labeling this as "future".

**Comment by richardm-stripe** [comment]
Fixed in #1629, released in https://github.com/stripe/stripe-node/releases/tag/v11.2.0
