### ISSUE TITLE
Unable to resolve module 'Crypto'

### ISSUE THREAD

**Issue by rasthana2012** [stripe/stripe-node#1027]
Using react-native version 0.63.2, I am getting error -

`Error: Unable to resolve module `crypto` from `node_modules/stripe/lib/utils.js`: crypto could not be found within the project.`

Crypto is deprecated library so I am installing it separately. Please help how to resolve this issue. I am getting same error in both iOS and Android.

**Comment by paulasjes-stripe** [comment]
stripe-node is meant to be used in the Node environment on the server, where `crypto` is a built in library. That means it won't work on a browser environment where the `crypto` library doesn't exist.

I expect you might want the Stripe React bindings instead of our Node bindings: https://github.com/stripe/react-stripe-js
