### ISSUE TITLE
The property "plan" was removed from Subscriptions.d.ts.

### ISSUE THREAD

**Issue by Phatsuo** [stripe/stripe-node#1037]
The property "plan" was removed from Subscriptions.d.ts.

https://github.com/stripe/stripe-node/commit/46d9040b3da082088eadf8be2a08a201658fc093#diff-4386ce01e3a52d5b6577befff0fb5869L151

I am using CustomersResource.retrieve() which returns a customer. The customer includes the subscription. The subscription includes a bunch of properties which have been removed... plan, quantity, status, etc. I am using the plan property, and now with the latest version, it is missing from the typescript definitions and this is causing a build error.

TS2339: Property 'plan' does not exist on type 'Subscription'.

There are no comments on the commit as to why these properties were removed.

Why was this removed? Is there some plan to deprecate these properties? Is there some other method we are supposed to use now to get the customers plan?

**Comment by remi-stripe** [comment]
@Phatsuo `quantity` and `plan` on `Subscription` have been deprecated for multiple years now. As we support multiple plans (or rather Prices now) per Subscription, those top-level properties are confusing since they are only set if you have one `SubscriptionItem`.

We removed them from the client libraries and also removed them from the API Reference for the Subscription resource [here](https://stripe.com/docs/api/subscriptions/object).

The properties are still _returned_ in the API since removing them would be a breaking change but we discourage using them which is why they are not in the types anymore. Instead of reading those resources top-level on `Subscription`, instead, look at the `SubscriptionItem`'s properties which are in `items`. Instead of accessing `customer.subscriptions.data[0].quantity` you would do `customer.subscriptions.data[0].items.data[0].quantity`. Same for `plan` though we also recommend using `price` instead.
