### ISSUE TITLE
VS Code Intellisense doesn't work with Stripe Node library

### ISSUE THREAD

**Issue by Lutrome** [stripe/stripe-node#1039]
Hello,

I'm trying to follow the Stripe "Accept a Payment" integration tutorial here: https://stripe.com/docs/checkout/integration-builder but Intellisense in VS Code (https://code.visualstudio.com/docs/editor/intellisense) does not seem to work with Stripe. Other Node modules are fine, though.

![image](https://user-images.githubusercontent.com/921778/95818609-1eda6d80-0cd9-11eb-8f69-3887de2576d3.png)

I'm using node@v12.18.2 and Stripe@8.111.0. Is there something I'm doing wrong?

**Comment by paulasjes-stripe** [comment]
Long story short, you can get VSCode's IntelliSense to automatically pick up types and method signatures if you use ES6 modules. 

Long story long, stripe-node dynamically generates its common class methods in order to reduce boilerplate code in the library. The downside is that this means IntelliSense can't automatically generate code hints from the code directly or from comments. Good news is that you can still get these hints since we recently shipped TypeScript definitions to go with the library, which will also work with regular JavaScript. Caveat is that you'll need to use ES6 modules for VSCode to correctly pick them up.

To do this just follow these steps:

1. Make you're on at least stripe-node version 8.0.0
2. Add the line "type": "module" to your package.json file in the root directory of your Node project
3. Use the import syntax to load the Stripe library: 

```
import Stripe from 'stripe';
```

You should now be able to see the Stripe typehints:

<img width="643" alt="Screen Shot 2020-08-07 at 3 22 52 PM" src="https://user-images.githubusercontent.com/46610432/95821993-a49ffc80-0d5d-11eb-8002-9205c1ee0edf.png">
