### ISSUE TITLE
Stripe webhook not working with firebase functions

### ISSUE THREAD

**Issue by Pldesch** [stripe/stripe-node#1043]
Hi,
I'm setting up a stripe webhook to fulfill my order with stripe after a payment while hosting it with firebase functions.
When developing on a localhost everything works fine until I publish it in a firebase function where it always sends me a [400] error. Creating the payment intent works fine in the same firebase function but that one doesn't.

The error message I get is : No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing

Code of my express backend :

```app.post(
  "/stripe/webhook",
  bodyParser.raw({ type: "application/json" }),
  async (request, response) => {
    const payload = request.body;
    const sig = request.headers["stripe-signature"];
    let event;

    try {
      event = stripe.webhooks.constructEvent(payload, sig, endpointSecret);
    } catch (err) {
      return response.status(400).send(`Webhook Error: ${err.message}`);
    }

    // Handle the checkout.session.completed event
    if (event.type === "checkout.session.completed") {
      const session = event.data.object;
      oldSession = await stripe.checkout.sessions.listLineItems(
        session.id,
        function (err, lineItems) {
          fulfillOrder(session, lineItems);
        }
      );
    }

    response.status(200);
  }
);

**Comment by remi-stripe** [comment]
@Pldesch The error indicates that we couldn't find a matching signature. This usually happens when the payload that we signed is different from the payload you are trying to verify, often because your framework/server is modifying the payload trying to be helpful.
There are unfortunately many possible root causes which depends a lot on your exact setup. What I usually recommend is to look into this issue https://github.com/stripe/stripe-node/issues/341 which has many different fixes from users based on their own integration path. Especially this one: https://github.com/stripe/stripe-node/issues/341#issuecomment-617193575

Otherwise, I'd recommend reaching out to our support team and providing more details, especially the exact payload you are receiving/parsing: https://support.stripe.com/contact
