### ISSUE TITLE
TypeScript SubscriptionDeleteParams is missing cancel_at_period_end

### ISSUE THREAD

**Issue by codeth** [stripe/stripe-node#1078]
[This interface](https://github.com/stripe/stripe-node/blob/master/types/2020-08-27/Subscriptions.d.ts#L1035) seems to be missing a key I'm expecting to be able to use:

```ts
interface SubscriptionDeleteParams {
  /**
   * Specifies which fields in the response should be expanded.
   */
  expand?: Array<string>;

  /**
   * Will generate a final invoice that invoices for any un-invoiced metered usage and new/pending proration invoice items.
   */
  invoice_now?: boolean;

  /**
   * Will generate a proration invoice item that credits remaining unused time until the subscription period end.
   */
  prorate?: boolean;
}
```

`cancel_at_period_end?: boolean` should also feature here, according to the [Stripe Subscription docs](https://stripe.com/docs/billing/subscriptions/cancel#canceling).

I did have a look around to see if this was a deprecated option, but couldn't find anything. Apologies if I've missed something!

Happy to stick a PR in if it is in fact missing.

**Comment by remi-stripe** [comment]
@codeth Thanks for the report! The `cancel_at_period_end` is a parameter on the Update Subscription API [here](https://stripe.com/docs/api/subscriptions/update#update_subscription-cancel_at_period_end) and not on the Cancel Subscription [API](https://stripe.com/docs/api/subscriptions/cancel) one, that's why it's not in that interface. That's also the API that the code example in that page is calling!

I hope this clarifies the confusion!

**Comment by codeth** [comment]
Ah sorry, totally missed that, my mistake! 🤦‍♂️ 

I think my confusion initially came from [here in the API docs](https://stripe.com/docs/api/subscriptions/object#subscription_object-cancel_at_period_end), where it sounds like it should be a param on the cancellation call:

> If the subscription has been canceled with the `at_period_end` flag set to `true`...

Thanks for your help!
