### ISSUE TITLE
typescript Stripe.Issuing.Authorization - type `incorrect_expiry`

### ISSUE THREAD

**Issue by alan345** [stripe/stripe-node#1089]
I received a new authorization with `(authorizationStripe as Stripe.Issuing.Authorization).request_history[0].reason === 'incorrect_expiry'`

Unfortunately when I want to catch this case, Typescript drops an error: 
`This condition will always return 'false' since the types 'Reason' and '"incorrect_expiry"' have no overlap.ts(2367)`

![image](https://user-images.githubusercontent.com/15246526/102118500-9ff6d380-3df4-11eb-8f1a-01ac87d5d20d.png)

It works well with other cases like: `insufficient_funds`  or `spending_controls` or `verification_failed`

Only `incorrect_expiry` is not a valid `ENUM` for `Stripe.Issuing.Authorization.RequestHistory.Reason`

**Comment by remi-stripe** [comment]
@alan345 the enum value `incorrect_expiry` has been deprecated for a while now and was only available for users in the Issuing beta before we released it publicly. On the latest version it's instead `verification_failed`. Because of this, it's not in our official Typescript definitions today.
Your account must have a custom setting enabled to match the beta version of the API instead. You will have to disable type verification for that line, or work with our support team to migrate your code to the latest version: https://support.stripe.com/contact
