### ISSUE TITLE
Missing type: Topups destination_balance

### ISSUE THREAD

**Issue by tmirmota** [stripe/stripe-node#1092]
when creating a topup with:

```
stripe.topups.create({
      amount,
      currency: 'usd',
      description,
      destination_balance: 'issuing',
      statement_descriptor: 'Top-up',
      source,
    })
```

`destination_balance: 'issuing',` gives a `'destination_balance' does not exist in type 'TopupCreateParams'` error

**Comment by remi-stripe** [comment]
@tmirmota This feature is what we call "gated" today which means only a subset of accounts have access to it and that's why it's not in type definitions for now. We recommend that you disable Typescript signature verification for that call for now and it will be added officially in the future once the feature ships more widely!

**Comment by tmirmota** [comment]
Makes sense Remi, thanks for the details!
