### ISSUE TITLE
Using price key instead of price_data for creating checkout session gives Missing required param error

### ISSUE THREAD

**Issue by mrunal012** [stripe/stripe-node#1114]
I am trying to create checkout session for product. created price id for product using stripe dashboard. 

```
const session = await stripe.checkout.sessions.create({
      mode: "subscription",
      payment_method_types: ["card"],
      line_items: [
        {
          price: priceId,
          quantity: 1,
        },
      ],
      success_url: `${domainURL}/success.html?session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${domainURL}/canceled.html`
});
```

above code returns 
`{"error":{"message":"Missing required param: line_items[0][currency]."}}`

while price_data key is working inside line_items and gives session id but project requirement is to use only price key and not price_data 

i am unable to find out the exact problem and way how to implement checkout with price id instead of price_data

**Comment by remi-stripe** [comment]
@mrunal012 Github issues should be limited to bugs with the library itself. This question is more an integration question and would be better handled by our support team that you can contact here: https://support.stripe.com/contact

To unblock you though, the issue is likely that `priceId` is an empty variable right now so it's ignored. Double check all your variables to make sure you send a valid Price id (price_123) as a parameter.
