### ISSUE TITLE
Balance transactions filtered by created returns empty array

### ISSUE THREAD

**Issue by cetchells** [stripe/stripe-node#1125]
Node v 12.0.0
Stripe Api v 8.137.0

I'm trying to pull in Balance Transactions  for Jan this year using created.gte and created.lte

`const balanceTransactions = await stripe.balanceTransactions.list({
  created:{
    gte:1609459201,
    lte:1612137599
  }
});`

It completes with success but the data array response is always empty, which I know is false.

`[
  {
    object: 'list',
    data: [],
    has_more: false,
    url: '/v1/balance_transactions'
  }
]`

I've tried making the unix timestamps strings but get the same as the docs state:
"The value can be **a string with an integer Unix timestamp**, or it can be a dictionary "
I can only think the timestamp format is wrong or its a bug?

**Comment by remi-stripe** [comment]
@cetchells I just tried that code locally with the exact timestamps you mentioned and the API is working properly and returning 10 BTs on my account.  Either your code is passing different timestamps or you don't have BTs on the account you are making a request on at the moment with the API key your code uses. Make sure to log the timestamps you are passing so that they are not in milliseconds instead of seconds for example.

I'm going to close this issue as it can't be a bug with the library itself but I'd recommend following up with our support team directly: https://support.stripe.com/contact
