### ISSUE TITLE
Missing 'plan' attribute type in Stripe.Subscriptions

### ISSUE THREAD

**Issue by Owpac** [stripe/stripe-node#1145]
Hello !

In a Subscription object, a **plan** attribute is present but not typed at all. We can see it just by doing a console.log on this api call:
```js
const subscriptions = await stripe.subscriptions.list({
      customer: customerId,
      status: 'active',
      expand: ['data.default_payment_method'],
});

console.log(subscriptions)
``` 

![image](https://user-images.githubusercontent.com/29702840/115698133-95c98080-a364-11eb-91dc-406de6898860.png)

It is really annoying for my team since we need this attribute and we use Typescript...

**Comment by remi-stripe** [comment]
@Owpac Thanks for reaching out. The types in stripe-node match what is officially documented in our API today. The `plan`p property on `Subscription` has been deprecated for multiple years already and was removed a few months ago from the docs and the types. It's in the API, so that we don't break any existing integration but not documented.
No one but legacy integrations should be using this. Instead, you should look at the `items` collection which is a list of `SusbcriptionItem` which are typed and have the `price` property which maps to the underlying `Price` associated with the Subscription: https://stripe.com/docs/api/subscriptions/object#subscription_object-items-data-price
