### ISSUE TITLE
payouts.create throws an error with an undocumented error code

### ISSUE THREAD

**Issue by joeythomaschaske** [stripe/stripe-node#1147]
When creating a payout when there are insufficient funds the sdk throws an exception.

```
{
    "errorType": "Error",
    "errorMessage": "You have insufficient funds in your Stripe account for this transfer. Your card balance is too low.  You can use the /v1/balance endpoint to view your Stripe balance (for more details, see stripe.com/docs/api#balance).",
    "code": "balance_insufficient",
    "type": "StripeInvalidRequestError",
    ...
}
```

This is a little tricky to error handle since `balance_insufficient` is not a [documented error](https://stripe.com/docs/api/payouts/failures) code, and I am guessing there are other errors that could happen when submitting a payout that are also not included in that list.

There is a note in the documentation about  *initial errors* but it doesn't go into detail what types of initial errors there are 

> Returns a payout object if there were no initial errors with the payout creation (invalid routing number, insufficient funds, etc). The status of the payout object will be initially marked as pending.

Ideally it would just return a `Payout` object with a status code of `insufficient_funds` instead of throwing an exception.

Is there a supplemental list of errors that can be thrown on submission of creating a payout to make this easier to handle?

**Comment by remi-stripe** [comment]
@joeythomaschaske Flagging that github issues should be limited to bugs with the library itself and this is more a question about our product. I'd recommend reaching out to our support team for help instead: https://support.stripe.com/contact

To unblock you though, I think there's a bit of a mixup. The `code` returned in the API is entirely separate. Those are document on the [Error codes](https://stripe.com/docs/error-code) doc which shows [`balance_insufficient](https://stripe.com/docs/error-codes#balance-insufficient) as an expected value. This error happens because your own account doesn't have enough funds to create the Payout. This means you're trying to send $100 to a bank account but that account's balance in Stripe is below $100 so it fails synchronously on Payout creation. All API errors raise an exception like this, it'd be the same if you passed `currency: "dollar"`instead of `currency: "usd"` for example. You can read more about error handling here: https://stripe.com/docs/api/errors

On the other hand, the payout failures [doc](https://stripe.com/docs/api/payouts/failures) you mentioned is for the `failure_code` [property](https://stripe.com/docs/api/payouts/object#payout_object-failure_code) on the Payout resource. This is the error returned by the bank itself after we sent a Payout to the associated bank account. Since we could debit your bank account for a negative balance it is possible for a Payout that was created to later fail asynchronously because your bank account had insufficient balance.

I hope the writeup helps! If you have follow up questions our support team can unblock you!
