### ISSUE TITLE
Installed payments / calculating correct subscription cancel_at date

### ISSUE THREAD

**Issue by taylorchance** [stripe/stripe-node#1150]
I'm having issues try to implement installed payments eg (4 payments of $25 every 2 weeks). Im trying to do this with a subscription that has a cancel_at date. Is this even the right way to do this? 

What is the exact date I need to cancel at so there is no proration period or extra payments / 4th payment isn't cancelled?

Please let me know, main Stripe support is useless.

**Comment by remi-stripe** [comment]
@taylorchance Github issues are limited to bugs and feature requests with the library itself. This is an integration question and asking our support team is the best path forward: https://support.stripe.com/contact You can also talk to other developers and Stripe engineers on IRC as we are on Freenode in #stripe and help people there too.

To unblock you though, I would highly recommend using Subscription Schedules instead of this: https://stripe.com/docs/billing/subscriptions/subscription-schedules

Calculating the correct `cancel_at` is quite tricky with things like DST and such and will always lead to a possible proration at the end of the last period which is unlikely to be what you want. Schedules solve this by letting you set exactly the number of cycles (iterations) you want to go through.
