### ISSUE TITLE
TypeError: .stripe.confirmCardPayment is not a function

### ISSUE THREAD

**Issue by JovanShandro** [stripe/stripe-node#1160]
I am using the following versions:
Node: v14.12.0
Stripe: 8.148.0

And this is my code:
```js
import Stripe from "stripe";

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY as string, { apiVersion: "2020-08-27" });
//...
  const { paymentIntent, error } = await stripe.confirmCardPayment(client_secret);
  if (error) {
    // Handle error here
    console.log("Error: ", error.message);
  } else if (paymentIntent && paymentIntent.status === "succeeded") {
    // Handle successful payment here
    console.log("Successful payment");
  }
```

However I get the following error form typescript:
```
Property 'confirmCardPayment' does not exist on type 'Stripe'.
```
I am not sure if this method has moved elsewhere, but I tried it as I found this:
https://stripe.com/docs/js/payment_intents/confirm_card_payment

Thank you!

**Comment by JovanShandro** [comment]
I also tried the following:
```js
  const { paymentIntent, error } = await ( stripe as any ).confirmCardPayment(client_secret);
```

As I thought it may be an issue with the types, but got the following error:
```
TypeError: stripe_1.stripe.confirmCardPayment is not a function 
```

**Comment by richardm-stripe** [comment]
Hello @JovanShandro,

I think that code is importing `stripe-node`, our library for server-side Javascript, but `confirmCardPayment` only exists on `stripe-js`, our library for browser-side Javascript. The `confirmCardPayment` function is something you can only do from the browser because it sometimes requires user interaction.

See our ["Accept a Payment"](https://stripe.com/docs/payments/accept-a-payment?platform=web&lang=node&ui=elements) doc for an example of how the responsibilities are divided between the server and the client.

I hope that clarifies things. Closing this issue out, but feel free to contact [our support team](https://support.stripe.com/) if you need additional assistance.
