### ISSUE TITLE
TS typing on stripe.accounts.createExternalAccount()

### ISSUE THREAD

**Issue by chrskerr** [stripe/stripe-node#1181]
Type ExternalAccountCreateParams expects `external_account` to be `string`, rather than `string | BankAccount` causing issue with the below code example.

The docs support this dual use of external_account key https://stripe.com/docs/api/external_account_bank_accounts/create

I'm using stripe version 8.157.0

Thanks!

```
stripe.accounts.createExternalAccount( stripe_id, {
  external_account: { 
	  object: "bank_account",
	  country: "AU", currency: "AUD", 
	  account_holder_name, 
	  routing_number,
	  account_number,
  },
   default_for_currency: true,
})
```

**Comment by remi-stripe** [comment]
@chrskerr While the API supports this feature, we want to avoid encouraging passing raw card details in that API and so for that reason we focus on the `string` option instead. You can disable type checking on that specific line if you pass raw bank account details instead of creating a Token (btok_123) client-side.

I'm going to close this out as it's been reported a few times but we'll discuss internally as a potential future improvement!
