### ISSUE TITLE
Error 141: Cannot read property 'client_secret' of null

### ISSUE THREAD

**Issue by JoonJoon123** [stripe/stripe-node#1189]
Hi there, I hope you are doing well.

I have been trying and trying for hours to get a 7 day free trial for my subscription for my app working but I keep getting the same error:
`{"code":141,"error":"Cannot read property 'client_secret' of null"}`

It works if I remove the "trial_period_days" input in the plan but I NEED the free trial working for my app.
I also tried to preset the trial_period_days from the stripe dashboard in the product pricing.
Here is my node js code:
```
const stripe = require('stripe')('sk_test_idnumber');

Parse.Cloud.define("paymentsheet", async (req) => {
  const customer = await stripe.customers.create();
  const ephemeralKey = await stripe.ephemeralKeys.create(
    { customer: customer.id },
    { apiVersion: '2020-08-27' }
  );
  const planz = await stripe.plans.create({
    amount: 5200,
    currency: 'usd',
    interval: 'year',
    trial_period_days: 7,
    product: 'prod_idnumber',
  });
  const subscription = await stripe.subscriptions.create({
    customer: customer.id,
    items: [
      { plan: planz.id }
    ],
    trial_from_plan: true,
    payment_behavior: 'default_incomplete',
    expand: ['latest_invoice.payment_intent'],
  });
  const cliSec = subscription.latest_invoice.payment_intent.client_secret;
  const custid = customer.id;
  const ephkey = ephemeralKey.secret;
  return {
    paymentIntent: cliSec,
    ephemeralKey: ephkey,
    customer: custid
  };
});
```

**Thanks in Advance and Stay Safe!! :)**

**Comment by remi-stripe** [comment]
@JoonJoon123 Github issues should be limited to bugs with the library itself. Here you're asking for help about your code and you should instead contact our support team: https://support.stripe.com/contact/email

To unblock you though, the `payment_intent` property would be null since there is no payment to complete on a free trial. You should look at `pending_setup_intent` instead and complete that `SetupIntent` to set up your card properly for their next invoice.
