### ISSUE TITLE
await stripe.subscriptions.create() doesn't run

### ISSUE THREAD

**Issue by echoi3** [stripe/stripe-node#1213]
I copied and pasted codes in this URL (https://stripe.com/docs/api/subscriptions/create) to my VSCode after changing customerId and priceId, consoled the output, but it looks like `await stripe.subscriptions.create()` doesn't run at all. Could anyone help me with this? I am using Typescript and React.

**Comment by remi-stripe** [comment]
@echoi3 Github issues should be limited to bugs with the library itself. Your question is more an integration question better suited for our support team https://support.stripe.com/contact. Otherwise you can also join our Discord server to get help from Stripe and other developers https://stripe.com/go/developer-chat
