### ISSUE TITLE
Subscription memo - TypeScript API

### ISSUE THREAD

**Issue by matthias-trip** [stripe/stripe-node#1220]
Hi all,

I'm trying to set the `Memo` for a new subscription using the API. When creating a new subscription using the Stripe Dashboard I can see the memo being set using the `invoice_settings ` dictionary.

`
...
"invoice_settings": {
    "description": "Thank you for your business!",
    "send_hosted_payment_email": "true"
  }
...
`

However, I don't see this anywhere in the TypeScript definitions. Is this not there for a reason? And if so, what would be the best way to set the memo on the subscription so all future invoices will include this memo?

Thanks!

**Comment by remi-stripe** [comment]
@matthias-trip This feature is not supported in the API today and only works in the Dashboard. That's why it's not in the type definitions in Typescript. It might ship in the future but we don't have a timeline for it.

Github issues should be limited to bugs with the library itself so I'm going to close this ou
