### ISSUE TITLE
Stripe.PaymentIntent type is incompatible with stripe-js version of PaymentIntent

### ISSUE THREAD

**Issue by imdavidmin** [stripe/stripe-node#1224]
Currently there are two type errors on copying a Stripe.PaymentIntent object (full privilege with secret key) into a client side PaymentIntent (publishable key)

First is last_payment_error:
```
Type 'import("stripe").Stripe.PaymentIntent.LastPaymentError' is not assignable to type 'import("@stripe/stripe-js").PaymentIntent.LastPaymentError'.
  The types of 'payment_method.customer' are incompatible between these types.
    Type 'string | Customer' is not assignable to type 'string'.
      Type 'Customer' is not assignable to type 'string'.ts(2322)
```

Second is payment_method:
```
Type 'string | PaymentMethod' is not assignable to type 'string'.
  Type 'PaymentMethod' is not assignable to type 'string'.ts(2322)
```

**Comment by remi-stripe** [comment]
@imdavidmin I'm sorry but I'm struggling to parse the report here with the details you shared. Would you be able to provide more context about what you're doing? For example, what is your code around the place where the error happens in your code. Where does the PaymentIntent resource come from (client-side or server-side) and could you provide a truncated response/JSON for the relevant parts for me to investigate further?

**Comment by imdavidmin** [comment]
Hi,

My client side code sends a request to the server to validate a basket. The server checks all the pricing is correct then creates a PaymentIntent object on the server side using a POST fetch. The response from that fetch is the full Stripe.PaymentIntent type. Returning this response back to the client will expose too much info, so I'm using the reducer function below to strip out the fields that are not available for publishable key.

```
// pi parameter should be of Stripe.PaymentIntent type - the server side PaymentIntent type definition
// But Stripe.PaymentIntent is incompatible with @stripe/stripe-js version of PaymentIntent. Issue filed on Github
function reduceStripePIToPublishableKeyPermissions(pi: PaymentIntent): PaymentIntent {
    return {
        id: pi.id,
        amount: pi.amount,
        client_secret: pi.client_secret,
        currency: pi.currency,
        description: pi.description,
        last_payment_error: pi.last_payment_error,
        next_action: pi.next_action,
        payment_method: pi.payment_method,
        payment_method_types: pi.payment_method_types,
        receipt_email: pi.receipt_email,
        setup_future_usage: pi.setup_future_usage,
        shipping: pi.shipping,
        status: pi.status,
        object: pi.object,
        canceled_at: pi.canceled_at,
        cancellation_reason: pi.cancellation_reason,
        capture_method: pi.capture_method,
        confirmation_method: pi.confirmation_method,
        created: pi.created,
        livemode: pi.livemode
    }
}
```

Hope this clears it up.

**Comment by remi-stripe** [comment]
@imdavidmin Thanks for the extra details. Just to make sure I understand, the issue here is unrelated to stripe-node and its types and is instead related to Stripe.js, our client-side library, and its own types? And you get an error because you are doing your own logic to truncate/redact the JSON yourself server-side, unrelated to stripe-node?

**Comment by imdavidmin** [comment]
@remi-stripe Well the type definition will need to change either on the stripe-node side or the stripe-js side. I don't know what business logic you guys want to have. Both PaymentIntent definitions are addressing the same JSON response from the REST API. 

I don't see how this is my input of my own logic as I'm simply copying like for like. The PaymentIntent definition of the client-side should be a subset of the server side definition.

Sure, I can do a work around by passing only the PaymentIntent ID back to the client side, and then use the client-side SDK to retrieve it again from Stripe. That seems like a silly extra step to add in just because the type definition was incompatible from the library. The actual data without type checking is the same.

**Comment by remi-stripe** [comment]
@imdavidmin From what I can tell, the problem is that server-side the `customer` property on `PaymentMethod` can be a `string` **or** a `Customer` object. This is due to the [Expand feature](https://stripe.com/docs/expand) which can be used server-side (and not client-side).

So when you retrieve the `PaymentIntent`, the `last_payment_error` can have the `PaymentMethod` object in it, and that could technically have the whole `Customer` object in `customer` because the types are identical to the top-level `PaymentMethod` object which it describes. This is reflected by the types in `stripe-node` for that reason [here](https://github.com/stripe/stripe-node/blob/master/types/2020-08-27/PaymentIntents.d.ts#L273)

Client-side though, the `customer` property can never be anything else than a `string` on `PaymentMethod` since it can't be expanded for security reasons. This means that inside `last_payment_error`, the type definition points to a `PaymentMethod` too but that one only supports `string` as defined [here](https://github.com/stripe/stripe-js/blob/master/types/api/PaymentMethods.d.ts#L30)

This does mean that, since you're the one turning a server-side PaymentIntent into a client-side PaymentIntent, you'll need to force the type for that specific part of the JSON (and possibly others) explicitly. You could also ignore `last_payment_error` in the returned property since it could have sensitive information such as the entire `Charge` object.

**Comment by imdavidmin** [comment]
Thanks @remi-stripe 

I had a further read and seems like for most operations on the front-end, the client only needs the client secret, and not other attributes in a PaymentIntent. I'm trying to use the PaymentIntent object as a single source of truth so that the displayed amount, currency etc on the UI matches what the PI will charge. 

In this case, I guess Stripe's preferred way is for me to pass from the server the client secret only, and then the client makes additional queries to Stripe's server as needed? There is no built in redaction function on the stripe-node library, I assume?

**Comment by remi-stripe** [comment]
Correct, there's no built-in redaction in stripe-node and it's not something we would add for now unfortunately. You could retrieve the PaymentIntent server-side with the publishable key I guess though it'd be the same as doing it client-side after passing the client_secret back.

I do understand wanting to pass more than just `client_secret`, like amount/currency, but I'd recommend doing this as your own object instead between your server-side code and client-side code.

I'm going to close as we've resolved the confusion. Don't hesitate to ask for help from developers on our Discord server: https://stripe.com/go/developer-chat
