### ISSUE TITLE
Stripe connection errors in Cloudflare workers

### ISSUE THREAD

**Issue by hansy** [stripe/stripe-node#1233]
I'm running into an issue where when I need to make an API request to Stripe from my Cloudflare Worker, I encounter `An error occurred with our connection to Stripe`. Using `maxNetworkRetries` doesn't seem to make any difference. I thought maybe the Workers were blocking external calls for whatever reason, but I haven't experienced any issues with other 3rd party endpoints.

Everything else with the library seems to be working fine, so I'm not sure what to do here. Any suggestions?

**Comment by remi-stripe** [comment]
@hansy This sounds more like a support question so I'd recommend working with our support team https://support.stripe.com/contact and they can help you debug this.

**Comment by remi-stripe** [comment]
Also flagging https://github.com/stripe/stripe-node/issues/997 which seems potentially relevant though I assume you'd have gotten a specific error if it was related for you.

**Comment by hansy** [comment]
@remi-stripe will do thanks. also I read through that thread but didn't encounter any of the issues posted there.

**Comment by dcr-stripe** [comment]
Hi @hansy - could you expand on how you are making this request and your environment? Are you using any polyfills for the Node `http`/`https` libraries in order to use this in Cloudflare Workers? 

We are currently working on implementing a new HTTP client that uses `fetch`, which should be compatible with Cloudflare workers and simplify this integration.
