### ISSUE TITLE
Document how to handle locales in stripe-node vs Stripe.js

### ISSUE THREAD

**Issue by tuukka** [stripe/stripe-node#1250]
The constructor `Stripe` in stripe-node does not seem to take an option `locale` although the one in Stripe.js takes one: `locale: A locale used to globally configure localization in Stripe. Setting the locale here will localize error strings for all Stripe.js methods. [...]` https://stripe.com/docs/js/initializing#init_stripe_js-options-locale

I wish I could get localised messages also from errors arising from the use of stripe-node. Would it make sense to document here how to best achieve this?

**Comment by remi-stripe** [comment]
@tuukka Unfortunately, this is not a feature we support today, which is why it's not documented. In most cases, server-side errors are what we call "developer facing" where we assume you will catch and log those yourself but otherwise display a generic error on your end. Alternatively, you can catch specific [error codes](https://stripe.com/docs/error-codes) to display your own localized error for those.

Errors client-side are designed to be shown to end customers directly which is why they support localization and why we support passing a locale in that specific case.

We know it'd be helpful if we could localize all errors even server-side, though as a developer debugging those is trickier for you if they are all translated for example. It's something we do hope to support in the future, and when we do it'll be directly usable on stripe-node and any other server-side library we offer!

I'm going to close this out, as it's less a feature request about the library itself and more one of the API, I hope it's okay!

**Comment by tuukka** [comment]
@remi-stripe Thank you for helping me! Going forward, I think any of this information would be useful to anyone new to stripe-node.
