### ISSUE TITLE
"plan" key is missing from Subscription interface

### ISSUE THREAD

**Issue by ecklf** [stripe/stripe-node#1263]
Hello there,

I am using `stripe.subscriptions.retrieve` and noticed a possible mistake in the type definitions of this library.

The above query can return a `plan` field of type `Stripe.Plan`.

![image](https://user-images.githubusercontent.com/8146736/135455061-7d0d8b13-4df1-490f-93c2-a4b87bf6f6d2.png)

I couldn't seem to find it in https://github.com/stripe/stripe-node/blob/master/types/2020-08-27/Subscriptions.d.ts#L155

```
"stripe": "^8.178.0"
```

**Comment by remi-stripe** [comment]
@ecklf the `plan` property top-level on `Subscription` has been deprecated since late 2017 when we introduced the ability to have multiple Plans (today called Prices) on one Subscription. Before that, there was only one subscription item so we gave direct access to it top-level, but when we added the ability to have more than one it didn't make sense to have one top-level. What we did was that we kept that property set if you only have one Plan (now Price) and otherwise it's null, for many years. While this still happens today (otherwise it'd be a breaking API change) we have cleaned up both our docs and the Typescript definitions (and other statically types libraries) to remove this deprecated property and ensure the majority of new integrations never rely on this.

You should be looking at the Price associated with each SubscriptionItem in the `items` sub-list on the `Subscription` instead of the deprecated top-level `plan` property.

I'm going to close this out as there's no issue with the library itself but I hope this clarified what you're seeing!
