### ISSUE TITLE
PaymentIntentCreateParams.PaymentMethodData does not support 'card' type

### ISSUE THREAD

**Issue by willbt** [stripe/stripe-node#1264]
Hello, 

I used the payment_method attribute in the paymentIntents.create function and received this error: 

`A token may not be passed in as a PaymentMethod. Instead, use payment_method_data with type=card and card[token]=tok_xxxx"`

So I tried to use the payment_method_data and set the type as 'card' as below: 
payment_method_data: { type: 'card', card: { token: 'tok_xxxxx' } },

However, with TypeScript this doesn't work as the interface  PaymentIntentCreateParams.PaymentMethodData does not support the 'card' type.  

I solved by casting to any before passing to .paymentIntents.create and it works. 

```
const stripeRequest = {
      amount: request.amount,
      currency: request.currency_code,
      application_fee_amount: 0,
      payment_method_types: ['card'],
      confirm: true,
      capture_method: 'manual',
      payment_method_data: { type: 'card', card: { token: 'tok_xxxx' } },
    };

    const res = await this._stripe.paymentIntents.create(stripeRequest as any);
```

**Comment by remi-stripe** [comment]
@willbt Thanks for the report. We avoid typing the `card` hash because it'd also contain types for passing raw card details server-side which requires a higher level of [PCI compliance](https://stripe.com/docs/security/guide#validating-pci-compliance). Passing a Token id (tok_123) like you do is definitely supported but it's seen more as a temporary migration path than a canonical integration path as you should be confirming the PaymentIntent client-side instead of server-side on creation. We don't have plans to add types for that scenario but casting as any should solve the issue as you found!
