### ISSUE TITLE
How to create Connect-ed accounts ? 

### ISSUE THREAD

**Issue by rudyhadoux** [stripe/stripe-node#1286]
Hi,

I would like to create Connect-ed accounts within a NodeJS lambda, to use with an Angular app.

I'm having trouble finding documentation. Or even better, examples.

Could you help me please ?

Thanks.

**Comment by remi-stripe** [comment]
@rudyhadoux Github issues should be limited to bugs with the library. This is an integration question asking for documentation so you should talk to our support team: https://support.stripe.com/contact

We have complete end to end guides for Connect though in our docs that cover all languages such as https://stripe.com/docs/connect/collect-then-transfer-guide And for creating accounts only you should look at Express accounts in https://stripe.com/docs/connect/express-accounts or Standard accounts https://stripe.com/docs/connect/standard-accounts

**Comment by rudyhadoux** [comment]
https://stripe.com/docs/connect/collect-then-transfer-guide is what I was searching for.
Thanks.

**Comment by rudyhadoux** [comment]
But it does not work...
errorType": "Error",
"errorMessage": "Connect platforms based in FR must create Custom accounts via account tokens. For documentation on account tokens, see https://stripe.com/docs/connect/account-tokens."

**Comment by remi-stripe** [comment]
@rudyhadoux the error message that you found and posted has a clear link to a clear doc about how to do this.

Just to restate: none of this is a problem with the stripe-node library and it is an integration question. Please work with our support team for help integrating this instead if you still have questions after reading the docs.

**Comment by rudyhadoux** [comment]
Yes BUT. 
1. Your french support team rarely responds to me.
2. The link is old javascript and HTML code. It is very far from Angular.

**Comment by remi-stripe** [comment]
We don't have any Angular guide though. We focus on simple Javascript which will work with any framework/client. Also, we strongly recommend letting us collect all the information and you hit this because you didn't follow the guide I recommended and likely tried to pass personal information via the API upfront which doesn't work in France. If you follow the guide though, you won't hit any issue, because you will create an Express or Standard account (depends on your business model) and then you let Stripe collect all relevant information.

Please chat with our support team, we do support in multiple languages and it doesn't have to be in French since you also speak English. You can also talk to developers on Discord: https://stripe.com/go/developer-chat

Github issues are not a public forum for help in this case and focus on bugs and feature requests on the library itself so this is not the right place to get further help

**Comment by rudyhadoux** [comment]
In that case, I am going to cope alone. Thanks a lot.
Both english or french support rarely answer to my questions, or with a lot of time.
Old javascript needs big transformations to bu successful.

**Comment by remi-stripe** [comment]
I did give you a clear solution (no need for any JS since you redirect to Stripe to collect information) and also gave you a clear link to our Discord server where Stripe employees help developers with their integration though.
