### ISSUE TITLE
Checkout session create payment_method_types should be optional

### ISSUE THREAD

**Issue by goatandsheep** [stripe/stripe-node#1317]
The [documentation for creating checkout sessions](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_method_types) says `payment_method_types` is an optional enum. However, if I don't include it in `stripe.checkout.sessions.create`, I get an error saying Missing required param: `payment_method_types`

**Comment by richardm-stripe** [comment]
Hello @goatandsheep,

The property `payment_method_types` is marked as optional because it is required in some circumstances and not others. For example

```javascript
stripe.checkout.sessions.create({
  success_url: "https://example.com",
  cancel_url: "https://example.com",
  mode: "subscription",
  line_items: [{price: "price_xyz", "quantity": 1}]
})
```
can succeed without specifying `payment_method_types`.

I hope that clarifies things. I am closing this issue it mainly relates to the API and its documentation, rather than the `stripe-node` library itself.

**Comment by goatandsheep** [comment]
Thank you very very much for explaining. I don't know if i fully understand but as you said it's either irrelevant or my understanding of the documentation so I'll work that out with support if needed.
