### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: You did not provide an API key

### ISSUE THREAD

**Issue by Nithur-M** [stripe/stripe-node#1353]
I am trying to initialie stripe as follows:
`const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);`

But it is throwing the following error:
UnhandledPromiseRejectionWarning: Error: You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.
    at res.toJSON.then.StripeAPIError.message (/xxxxx/server/node_modules/stripe/lib/StripeResource.js:214:23)

**Comment by paulasjes-stripe** [comment]
I'm closing this since this issues page is for bugs and problems with the library itself, this looks like an integration issue.

I'd check that the contents of `process.env.STRIPE_SECRET_KEY` actually look like a Stripe secret key `sk_test_123`. I suspect that instead it's `undefined`, which would mean you need to add it to your `.env` file.

In the future if you are experiencing issues like this I suggest either writing into Stripe support at https://support.stripe.com/contact or joining the Stripe Developers Discord https://stripe.com/go/developer-chat.
