### ISSUE TITLE
Stripe.Issuing.Authorization.RequestHistory.Reason missing "authorization_controls"

### ISSUE THREAD

**Issue by kuang** [stripe/stripe-node#1356]
node: v17.3.1
stripe: v8.197.0

see title- the current enum list in `Stripe.Issuing.Authorization.RequestHistory.Reason` is:

(https://github.com/stripe/stripe-node/blob/master/types/2020-08-27/Issuing/Authorizations.d.ts#L263)

`          type Reason =
            | 'account_disabled'
            | 'card_active'
            | 'card_inactive'
            | 'cardholder_inactive'
            | 'cardholder_verification_required'
            | 'insufficient_funds'
            | 'not_allowed'
            | 'spending_controls'
            | 'suspected_fraud'
            | 'verification_failed'
            | 'webhook_approved'
            | 'webhook_declined'
            | 'webhook_timeout';
`

however, we noticed when we were testing cardholder spending control logic the reason coming back for declines is `authorization_controls` instead of `spending_controls`.

example authorization id: iauth_1KWnayHfjraEeTGYc5BHQPwW

**Comment by yejia-stripe** [comment]
Your Stripe account may be feature flagged so that it is using the Legacy Issuing API. Unfortunately, the types in stripe-node are only able to reflect the values in the latest, unflagged version of the API. We recommend either using `@ts-ignore` or `any` in these cases, or following the [migration guide](https://stripe.com/docs/issuing/migration-from-beta).
