### ISSUE TITLE
Upgrade when.js dependency

### ISSUE THREAD

**Issue by cowwoc** [stripe/stripe-node#138]
Please update the `when` dependency to the latest version (3.7.2 as of this writing) to fix this bug: https://github.com/cujojs/when/pull/366

**Comment by SlexAxton** [comment]
I've replaced `when` with `bluebird` as that seems to have the most community love. I went ahead and updated other dependencies, and got the tests passing again. Out as `3.2.0`.

I would like to mention that it'd *usually* be a bad idea to use webpack on `stripe-node` - since it requires your *private* key to do much of anything. It usually should be running on a well-secured server.

If you're looking for the client-side piece of the puzzle we do have stripe.js -- hosted at https://js.stripe.com/v2/ -- with docs here: https://stripe.com/docs/stripe.js

Thanks for letting us know about the bug!
