### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by cowwoc** [stripe/stripe-node#139]
I'd like to use stripe with https://github.com/webpack/webpack (similar to Browserify).

Is it possible for you to combine https://js.stripe.com/v2/ with this codebase so it runs against both node.js and browsers?

The current codebase fails on browsers due to the invocation of `uname` and reading of files from disk.

**Comment by matthewarkin** [comment]
You don't really want to be running server-side stuff in a browser, since that means that your secret key will be visible to anyone, and thats bad since your secret key is well a secret.

Also you don't want to run Stripe.js from your own local version of it, its no longer supported (well it was never really supported but now it will yell at you if you try it). Stripe.js gets updated a bit and you want to make sure you're using the latest version, especially now that its been re-architected to support PCI DSS 3.0

**Comment by cowwoc** [comment]
Agreed. Thanks for the clarification.

It might help if you published usage instructions for CommonJS (used by Browserify and Webpack). Meaning, provide documentation that explains why local bundling should not be used and recommend the use of something like https://github.com/ded/script.js/ if someone really wants to pull the library from Javascript code.

**Comment by SlexAxton** [comment]
I don't think you'd want to use a script loader either. You simply shouldn't run this code in an uncontrolled public environment, because it touches secret keys.

Stripe.js is a totally different project for the client side portion of using stripe. Due to PCI restrictions, you must load it from our domain at: https://js.stripe.com/v2/

Thanks!

**Comment by cowwoc** [comment]
@SlexAxton The script loader in question does what you want (download the Javascript at runtime). The only difference is that it allows you to do so from within another Javascript file. Anyway, I guess this doesn't really matter either way. I get your point. Thanks.

**Comment by okasha93** [comment]
just put stripe script `<script src="https://js.stripe.com/v3/"></script>` on the head of your **index.html** page
