### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by tkdan235** [stripe/stripe-node#141]
I am using the stripe module to validate coupons.  I get the following output from my node server if I enter a bad coupon:

```
Error: Can't set headers after they are sent.
  at SendStream.headersAlreadySent (/Users/daniel/Projects/testapp/node_modules/express/node_modules/send/lib/send.js:312:13)
  at SendStream.send (/Users/daniel/Projects/testapp/node_modules/express/node_modules/send/lib/send.js:462:17)
  at /Users/daniel/Projects/testapp/node_modules/express/node_modules/send/lib/send.js:439:10
  at Object.oncomplete (fs.js:107:15)
```

I suspect the this is occurring from the stripe module, but obviously the above error shows the error coming from `node_modules/express/`.  I simply can't reproduce it elsewhere and cannot find any place where I am setting request headers after they are sent.  This app is built using backbonejs if that makes any difference.

I should also note that other than that error above, the error and response is working fine for me.  So this is not a show stopper, just irritating.

**Comment by SlexAxton** [comment]
I can't reproduce this issue, but it makes a little bit of sense since we recently added per-request header support.

Here's the relevant commit: https://github.com/stripe/stripe-node/commit/74b06d84a515bca0e4c27a88aafb56fe0ce7c26c

Does anything stand out to you as something that would be causing this (maybe in conjunction with code that you wrote)?

/cc @kyleconroy
