### ISSUE TITLE
Missing types for interface Stripe.Event.Data.Object fails to compile

### ISSUE THREAD

**Issue by itaied246** [stripe/stripe-node#1449]
### Describe the bug

Missing types for `interface Stripe.Event.Data.Object`

### To Reproduce

```typescript
namespace Data {
  interface Object {}

  interface PreviousAttributes {}
}
```
Running `event.data.object.mode` fails to compile.

### Expected behavior

To compile and include the types

### OS

Ubuntu

### Node version

Node v16.15.0

### Library version

stripe-node@9.5.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@itaied246 `Object` on an `Event` can be any of our API resources. We don't have specific types for it since it depends which `type` of `Event` you're receiving. This means you can't just access `data.object.url` and have to first cast `data.object` to the right type and then you can access its `url` property.

**Comment by itaied246** [comment]
Do these events have types?
Does the library offer type guard casting?
