### ISSUE TITLE
subscriptions.retrieve() type is missing 'plan' property - although it IS available on the return

### ISSUE THREAD

**Issue by MichaelAJay** [stripe/stripe-node#1488]
### Describe the bug

In API version 2020-08-27, subscriptions.retrieve() returns an object with a 'plan' property.  This is very useful - but it's not documented in either the API documentation or the TypeScript declaration file.

### To Reproduce

const sub = await  stripe.subscriptions.retrieve(subscriptionId, { expand: ['default_payment_method'] }

In debug mode, behold the wonderful 'plan' property on the response.

Check the TypeScript file and grimace at the missing 'plan' property.  Or try to use sub.plan and grimace at the TypeScript problem "Property 'plan' does not exist on type Response<Subscription>"

### Expected behavior

The 'plan' property should be usable, should exist on the TypeScript declaration file, and should exist in the API documentation.

### Code snippets

```JavaScript
console.log(sub.plan) WILL break compliation with TS2339.  Adding // @ts-ignore before it WILL log the plan to the console.
```

### OS

Windows

### Node version

Node V16.15.1

### Library version

stripe 9.12.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
The top-level `plan` property has been deprecated since 2017 when we introduced the ability to have more than one Plan per subscription. Since then we also moved away from Plan and onto the new/unified Price API.

While `plan` is returned right now, it only happens if your subscription has exactly one Plan/Price and you should basically never rely on it.

Instead, look at `items[data][][price]` in the API which would be the Price(s) that are associated with your Subscription: https://stripe.com/docs/api/subscriptions/object#subscription_object-items-data-price
