### ISSUE TITLE
cannot create bank object  with bank details

### ISSUE THREAD

**Issue by rubiin** [stripe/stripe-node#1490]
### Describe the bug

I am trying to create a bank object with the createSource method by giving key value pairs instead of string.
However I am getting typing issue . Also the documentation is vague if we were to pass in bank details instead of source id

### To Reproduce

 1. Create a customer
 2. Craete a bank object with bank details on the customer

### Expected behavior

The method should create bank object with bank properties passed

### Code snippets

```JavaScript
customers.createSource(
  "cus_...",
  { source: {
    object: "bank_account",
    account_number: "110000000",
    routing_number: "000123456789",
    country: "US",
    currency: "usd",
  },
```
```


### OS

Linux

### Node version

16.15

### Library version

latest

### API version

2020-08-27

### Additional context

_No response_

**Comment by remi-stripe** [comment]
First off, I would strongly recommend using the PaymentMethod API instead as we rebuilt our ACH Debit integration entirely. Please carefully read https://stripe.com/docs/payments/ach-debit and related docs which go over how to do this in details. It also encourages you to collect bank account details **client-side** securely instead of having access to those server-side which is dangerous and increases your security burden (and PCI compliance burden if you do the same for cards).

Ultimately though the code you have works just fine, it's just old and discouraged. There are no types for this, both because it's deprecated and because we discourage passing raw bank account details server-side. If you want to move forward with that approach, you will have to explicitly suppress the type errors on that code.

I'm going to close this out as this is more an integration support question and not really a bug with the library. If you have follow up questions, please work with our support team directly: https://support.stripe.com/contact
