### ISSUE TITLE
Include tos_acceptance.service_agreement field in the API

### ISSUE THREAD

**Issue by itaied246** [stripe/stripe-node#1522]
### Is your feature request related to a problem? Please describe.

I need to create a checkout session with a conditional `on_behalf_on` depending if the connected account is "full" or "recipient".

### Describe the solution you'd like

I want to retrieve the account and check its `service_agreement`.
```js
const account = await stripe.accounts.retrieve(stripe_connected_account_id)
account.tos_acceptance.service_agreement === "full" ? ...
```

### Describe alternatives you've considered

The only way to do it now is by retrieving the account and checking its capabilities.
This solution does not guarantee that the correctness of the `service_agreement` and it has many pitfalls.

### Additional context

It is documented [here](https://stripe.com/docs/api/accounts/object#account_object-tos_acceptance-service_agreement) that this data exist, but it doesn't return that field.

**Comment by remi-stripe** [comment]
The `service_agreement` is returned if it was set to `recipient`, otherwise it's `null`. This means that you can assume it's not `recipient` unless it's present and set to `"recipient"`.

I'm going to close as this isn't a feature request for stripe-node, it's a request for our API. You can flag this to our support team who can escalate with the engineering team (though I will flag too).
