### ISSUE TITLE
Wiki page out of date?

### ISSUE THREAD

**Issue by brutalhonesty** [stripe/stripe-node#153]
Within the https://github.com/stripe/stripe-node/wiki/Passing-Options wiki page, refund() is the method shown but according to https://stripe.com/docs/api/node#create_refund, it should be createRefund().

On that note, should the syntax for it be the following?

```javascript
stripe.charges.createRefund(charge.id, {
   metadata: {
     'description': 'Some description.'
   }
}, function (error, refund) {
  if(error) {
    // Handle error.
  }
  // Handle refund.
});
```

My current error using the above syntax is:

```bash
/path/to/project/node_modules/stripe/lib/StripeMethod.js:57
      throw new Error(
            ^
Error: Stripe: Unknown arguments ([object Object],function (error, refund) {
      if(error) {
        return cb(error);
      }
      refunds.push(refund);
      return cb(null);
    }). Did you mean to pass an options object? See https://github.com/stripe/stripe-node/wiki/Passing-Options.
    at Object.createRefund (/path/to/project/node_modules/stripe/lib/StripeMethod.js:57:13)
```

**Comment by matthewarkin** [comment]
Hey @brutalhonesty, refund still does work, its a bit legacy from one charges only could have 1 refund, but the syntax it demos is right. I believe the issue here is you just have an old version of the Stripe package.

I remember seeing that error before and updating the npm package fixed it. I forgot which commit fixes the bug though

**Comment by brutalhonesty** [comment]
@matthewarkin Thanks for getting back to me. I'm on version 3.0.0. I'll bump it and see if it fixes. Thanks!
