### ISSUE TITLE
Radar options field `skip_rules` not defined in API spec

### ISSUE THREAD

**Issue by ay18** [stripe/stripe-node#1536]
### Describe the bug

https://stripe.com/docs/api/errors#errors-payment_method-radar_options-skip_rules

The field `skip_rules` doesn't seem to be defined in the API spec, leading to type errors with TS.

### To Reproduce

1. In service code, `import Stripe from "stripe";`
2. Try to set  `skip_rules` on type `Stripe.PaymentIntentCreateParams.RadarOptions`.
3. Field is not defined.

### Expected behavior

1. In service code, `import Stripe from "stripe";`
2. Try to set  `skip_rules` on type `Stripe.PaymentIntentCreateParams.RadarOptions`.
3. Field is of type `str[]` or `'all'[]`.

### OS

macOs

### Node version

^14.17.14

### Library version

stripe-node ^10.6.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
Thanks for the report @ay18. The feature you use is "secret" and not public. You can see this because it will say `Preview feature` next to it in the API Reference and you can't access it in a private browsing window where you're not logged in. 

Private/secret/beta features are not in our client libraries and the types since they are by definition secret. So until this feature goes public, there is no type for it.

I'm going to close this out since it explains the problem and the type would be fixed if we shipped that feature publicly in the future. Please work with our support team at https://support.stripe.com/contact if you have follow up questions on this overall feature.
