### ISSUE TITLE
Apple Pay with Customer Objects

### ISSUE THREAD

**Issue by knightcode** [stripe/stripe-node#154]
The end result of the iOS SDK is a token object that comes up to the server. Right now, I'm successfully creating a new charge with it, but the charge object is in no way tied to the customer object that we previously created when the customer onboarded with us. The docs suggest that I can create an new Card object for the Apple Pay token, but then on a subsequent order from that same customer, how am I to determine that I've already created a Card object with this token. And what if the customer selected a different credit card in the Apple Pay UI. What API call matches a Token to existing cards for that customer?

I'd actually prefer if setting the `customer` field of the Charge object did NOT generate an error for Apple Pay payments. Specifically, this error:
```
Error: Customer ******* does not have a linked card with ID ***********.
     at Error._Error (/......./node_modules/stripe/lib/Error.js:12:17)
     at Error.Constructor (/........./node_modules/stripe/lib/utils.js:113:13)
     at Error.Constructor (/........../node_modules/stripe/lib/utils.js:113:13)
     at Function.StripeError.generate (/........./node_modules/stripe/lib/Error.js:56:14)
     at IncomingMessage.<anonymous> (/............../node_modules/stripe/lib/StripeResource.js:136:39)
```

**Comment by matthewarkin** [comment]
It depends if you always want to use Apple pay or if you want to provide your own card selector or if you want to be able to bill the cards without the user Apple Paying each time.

For the first you can just add the token to the customer and bill that customer + card id (you can then just delete the card from the customer if you want to keep it organized).

For the other two, you can compare the fingerprint of the token (you can get this when you retrieve the token server-side) to the fingerprints of the customer's saved cards. If a fingerprint already exists, I'd recommended deleting the matching card and adding the new token, else just add the token and charge the customer and card id. 

I'm assuming the error you pasted says 

    Customer cus_******* does not have a linked card with ID tok_*****.

Note the tok_ instead of a card_. Specifying a customer id and a token isn't available for anything, its not specific to ApplePay.

**Comment by knightcode** [comment]
You're correct in assuming the text of the error printed. Sorry if I misused the terminology.

I'd rather have them Apple Paying every time. It's no extra work for the customer, and it kind of defeats the purpose if they don't. Or maybe I'm misunderstanding the purpose of the token Apple Pay is or should be giving the Stripe SDK.

Third, not to be contrarian, but that sounds like a lot of work to do on our server.

The anonymous charges showing in our Stripe Dashboard aren't the end of the world... arguably, that adds to the privacy/security in using Apple Pay. So, if need be, we'll live with it.

**Comment by matthewarkin** [comment]
Yeah, if you're going to use Apple Pay each time, then you can either just skip the creating a customer and have charges with no customers (then just keep track of it in your own database).

Or just everytime a customer apple pays, set the customer card/source to that token (don't add one) and charge that customer. So at most the customer will just have the latest card stored.

**Comment by billinghamj** [comment]
Honestly, this seems quite short-sighted. Apple Pay tokens are intended to be single-use, unless you're using them to set up recurring payments.

It's a very common use-case to use a token once on an existing customer. Seems to me something which Stripe should support better.

Given Stripe's current lack of support, I am planning on doing the following:

```js
const customerId = 'cus_blahblah';
const tokenId = 'tok_foobar';

const source = await stripe.customers.createSource(customerId, { source: tokenId });

const charge = await stripe.charges.create({
  amount: 500,
  currency: 'gbp',
  customer: customerId,
  source: source.id,
  capture: false,
});

stripe.customers.deleteSource(customerId, source.id).catch(error => {
  console.warn('failed to delete one-time-use source', card.id);
});
```

Could you confirm that this would work? Specifically, removing the source _immediately_ after charging it.

**Comment by matthewarkin** [comment]
If you want to charge a Stripe customer, you'd have to save the token to a customer, you can delete the source after you create the charge. Your code would work.

You could just charge the token directly and not save the source to a Stripe customer and instead in your own database do some linking of user ids to charges.

A discussion of whether or not you should be able to specify a customer id and a token (instead of a source id) for creating charges would be a good discussion for the [api-discuss mailing list](https://groups.google.com/a/lists.stripe.com/forum/#!forum/api-discuss)

**Comment by billinghamj** [comment]
Thanks. Made a post: https://groups.google.com/a/lists.stripe.com/forum/#!topic/api-discuss/Ue8pU-ya09o
