### ISSUE TITLE
Read error after subscription is cancelled

### ISSUE THREAD

**Issue by tracend** [stripe/stripe-node#157]
I noticed that the API doesn't like requesting the subscription's details using ```customers.retrieveSubscription``` after the subscription is cancelled. 

What is the proposed method to verify if a subscription is active and get the details of an expired subscription?

**Comment by freshlogic** [comment]
I've had some success retrieving the customer's past invoices to piece together if the customer was previously subscribed to a plan. Not sure if that works for your use case but it worked for me.

**Comment by tracend** [comment]
That could work, although more logic steps need to be chained for a rather common scenario. 

It would be simpler if the canceled subscription was available - there is a ```status``` attribute after all :)

**Comment by matthewarkin** [comment]
Yeah, I wrote an API-Discuss email about some of the weirdnesses when you delete an object in Stripe. When you delete anything but a customer you'll get a 404 when you try to do something to it which results in an invalid_request_error with a message like `Customer cus_5rN05UzPUl83rE does not have a subscription with ID sub_5rN0SVU1ZMuhsA` and the param of the error set to `subscription`. Basically since the retrieval of a subscription resulted in a 404 you can assume it was deleted.
