### ISSUE TITLE
Products API is not returning the optional features list

### ISSUE THREAD

**Issue by joaopcm** [stripe/stripe-node#1595]
### Describe the bug

With the following code block:
```js
const prices = await stripe.prices.list({
  expand: ['data.product'],
})

console.log(prices.data)
```

we can't see the optional `Feature list` we can fill out through the Stripe web dashboard, as this screenshot shows:
![image](https://user-images.githubusercontent.com/58827242/199143817-67213993-4ce8-41f3-b8ab-360f50688cfa.png)

### To Reproduce

1. Fetch all the prices/products from your Stripe account;
2. Fill out the `Features list`;
3. Try to get these optional data accessing `feature_list`, `features`, `features_list`, etc (it doesn't exist);

### Expected behavior

I want to render the features list on my website. I'd use that field to list all the features each subscription has.

### OS

macOS

### Node version

Node v16.16.0

### Library version

v10.15.0

### API version

2022-08-01

**Comment by remi-stripe** [comment]
@joaopcm This isn't really a bug with the stripe-node library so I'm going to close. The API doesn't return this because it is not something that is supported today. This feature is only available in the Dashboard for now. Please work with our support team directly to register your interest for this feature which will help us prioritize it in the future: https://support.stripe.com/contact
