### ISSUE TITLE
Does stripe TypeScript affect perfomance on build ?

### ISSUE THREAD

**Issue by ajarouih** [stripe/stripe-node#1605]
### Describe the bug

We’re also seeing very long compile times after adding the stripe package to our project. I have yet to see it finish compiling if we reference anything from stripe.

Commenting out the import Stripe from 'stripe'; line causes the slowness to disappear.

### To Reproduce

""

### Expected behavior

Fast build

### Code snippets

```JavaScript
"incremental": false
```

### OS

macOS

### Node version

v16

### Library version

latest

### API version

2022

### Additional context

Also changing out the incremental:false make it faster

**Comment by pakrym-stripe** [comment]
It's expected that the compilation time will increase a very small amount because the compiler has to parse more files. But it shouldn't result in long hangs and complete inability to compile.

To illustrate in the clean environment:

```bash
> npm install stripe --save
> npm install typescript --save-dev

>cat package.json
{
  "dependencies": {
    "stripe": "^10.16.0"
  },
  "devDependencies": {
    "typescript": "^4.8.4"
  }
}

> cat index.ts
import Stripe from "stripe";
const s = new Stripe("api_key", {apiVersion: "2022-08-01"})

# compile file with Stripe import
> time npm exec tsc index.ts
npm exec tsc index.ts  3.57s user 0.19s system 242% cpu 1.549 total

# change index.ts to be empty
> echo "" > index.ts
# compile an empty file
> time npm exec tsc index.ts
npm exec tsc index.ts  3.05s user 0.14s system 247% cpu 1.291 total
```

On my machine adding a Stripe reference adds <0.5s to the compilation time.

It's possible that in your setup there is something else that causes compilation time issues. Are you on a fresh version of TypeScript? Are there other plugins/extensions that run during the compilation (linting/minification/etc)?

**Comment by pakrym-stripe** [comment]
Closing as there was no engagement for some time. Please reopen if you still have issues with typescript performance when referencing Stripe SDK.

**Comment by shreyas-jadhav** [comment]
Once i have installed stripe, my vscode performance has become terrible, and next.js compilation or tsc hangs!

My problem was with this code:
```
  const customerFormMethods = useForm<Stripe.Customer>();
```

if i remove the generic type it works.
