### ISSUE TITLE
Sanitization of checkout session data during creation

### ISSUE THREAD

**Issue by vegandiet705** [stripe/stripe-node#1645]
### Is your feature request related to a problem? Please describe.

When a session is created using `stripe.checkout.sessions.create`, the data in the session seems to not be sanitized against database injection attacks. I would like to request this feature to be implemented.

### Describe the solution you'd like

When a session is created using `stripe.checkout.sessions.create`, the data in the session is sanitized against database injection attacks so that I don't need to worry with further sanitization.

### Describe alternatives you've considered

I thought of sanitizing the data using `express-validator` middleware. But the data used to create a session doesn't seem to come from the request body. Or does it come ?

How do you proceed to sanitize data after session creation ?

### Additional context

I'm using `express` on server side and `Stripe Checkout` for payments.

**Comment by remi-stripe** [comment]
When you create a Checkout Session you pass some information in the parameters this API supports ([doc](https://stripe.com/docs/api/checkout/sessions/create)). The rest can be filled out by customers directly on Checkout and then are part of the API through the relevant object(s) it will create.

We don't really do any kind of sanitization in the API and this is something you would handle on your own really the same way you would for any input your have in your own application or website. I don't see a world where we'd sanitize the data since we don't control what the caller (your code and anyone else's code) does with it.

I'm going to close this out as I don't think it's a feature request for stripe-node we would implement. Don't hesitate to talk to our support team if you have questions about your own code and your integration and they would be happy to help: https://support.stripe.com/contact
