### ISSUE TITLE
(node:10932) UnhandledPromiseRejectionWarning: Error: An error occurred with our connection to Stripe.

### ISSUE THREAD

**Issue by LeeCareFree** [stripe/stripe-node#1651]
### Describe the bug

connect fail

### To Reproduce

[example](https://stripe.com/docs/payments/quickstart?client=html&lang=node)

### Expected behavior

connect success

### OS

windows

### Node version

14.18.1

### Library version

9.0.0

### API version

/create-payment-intent

**Comment by remi-stripe** [comment]
@LeeCareFree What is the ask you have here? Is it why you have that error? Because if so, it looks like a network error here, something on your server blocking your access to Stripe. In that case, I would recommend contacting your host provider directly instead or working with our support team as it's more an integration help: https://support.stripe.com/contact
