### ISSUE TITLE
product.list needs to retrieve feature list

### ISSUE THREAD

**Issue by matthew-boston** [stripe/stripe-node#1702]
### Is your feature request related to a problem? Please describe.

I have been trying to receive the feature lists from a product but am currently unable to find a solution on how to do this. 

### Describe the solution you'd like

For the feature list to be retrieved when you make a request to 
``` 
const products = await stripe.products.list({
  limit: 3,
});
```
This would then return all data plus the feature list.

**Comment by anniel-stripe** [comment]
Hi @matthew-boston , thanks for submitting this issue ! As mentioned in https://github.com/stripe/stripe-node/issues/1495 and https://github.com/stripe/stripe-node/issues/1595, feature lists is still a Dashboard-only API, which means it's not publicly available yet, unfortunately.

Please work with our support team directly to register your interest for this feature which will help us prioritize it in the future: https://support.stripe.com/contact

**Comment by michealroberts** [comment]
@anniel-stripe Why has this been closed, when it has a tag of feature request, and is probably fairly easy to implement? This should be left opened until the API provides the data and the SDK provides the returned fields ...

**Comment by anniel-stripe** [comment]
Hi @michealroberts ! Apologies for the confusion - we generate our SDKs to reflect what is defined in [the public API](https://github.com/stripe/openapi), and we have internal processes separate from the SDK release process to bring new APIs public. So Dashboard-only APIs like this one aren't included in the SDKs since they're not public yet. I closed this issue because this is a feature request for the API and not stripe-node specifically, and unfortunately GitHub issues are not a very visible way to track this type of request. 😞

I asked around internally and the good news is that we've recently started the process of bringing this API public. Again, I'm sorry that my original answer wasn't very helpful, and we appreciate your patience!
