### ISSUE TITLE
StripeEmitter not supported in Vercel edge runtime

### ISSUE THREAD

**Issue by f-elix** [stripe/stripe-node#1732]
### Describe the bug

When deploying my server code as a Vercel edge function, stripe-node causes a crash with the following error from `stripe/esm/StripeEmitter.js`:

```
TypeError: Class extends value undefined is not a constructor or null
```

I suspect this is because the class `_StripeEvent` extends the `Event` Web API, but Vercel edge runtime doesn't support it as you can see here https://edge-runtime.vercel.app/features/available-apis.

This prevents me from using Stripe on the edge with Vercel.

Note that I am not sure if this is something that can/should be fixed by Stripe or Vercel.

### To Reproduce

Deploy an edge function on Vercel with the following code:

```ts
import Stripe from 'stripe';

const stripe = new Stripe(STRIPE_SECRET_KEY, {
	apiVersion: '2022-11-15',
	httpClient: Stripe.createFetchHttpClient()
});
```

### Expected behavior

The function should not crash.

### OS

macOS

### Node version

Node v18.12.0

### Library version

stripe-node v11.16.0

### API version

2022-11-15

**Comment by anniel-stripe** [comment]
Hi @f-elix , thanks for the bug report. I was able to reproduce this in a Vercel edge function, and I agree this seems to be because the Vercel edge runtime does not support the `Event` Web API. I'd suggest that you open an issue with Vercel, as `Event` and `EventTarget` are part of WinterCG's [Minimum Common Web Platform API](https://common-min-api.proposal.wintercg.org/#index) proposal, so I believe they'd want to support it there.

**Comment by f-elix** [comment]
Ok that sounds good, thank you! Feel free to close this if you like.
