### ISSUE TITLE
stripe module is imported as 'any' type

### ISSUE THREAD

**Issue by erjok** [stripe/stripe-node#1740]
### Describe the bug

I've added stripe node library as per Quickstart documentation:

`$ npm install --save stripe`

But imported type is not a function - it's any object

```
const stripe = require('stripe'); // any
const stripe = require('stripe')('sk_123'); // any
```

Obviously, this object doesn't have any intellisense

```
stripe
 .checkout // any
 .sessions // any etc

```

### To Reproduce

1. Install stripe module
2. Require module
3. No type definitions on the returned object

### Expected behavior

Expected a function to be returned.
Expected a Stripe object to be returned when the function is executed.

### OS

Windows 10

### Node version

Node v18.13.0

### Library version

11.17.0

### API version

NOT RELEVANT

**Comment by richardm-stripe** [comment]
It looks like this is typical behavior of Typescript for all libraries, not just `stripe-node`. Most likely the type definition for `require` comes from `@types/node` [where it is defined as returning](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/globals.d.ts#L252) `any`.

I'm closing this ticket as I don't think there's action to take. I don't think we should start changing docs to recommend `import` syntax instead of `require('stripe')('sk_123')` because ES modules is not the default in NodeJS, and after all the name of the library is `stripe-node`.
