### ISSUE TITLE
Adding Idempotent to Request causes "Must provide source or customer" error.

### ISSUE THREAD

**Issue by jimmiebtlr** [stripe/stripe-node#175]
Using Meteor with stripe-node version 3.3.4.  Dashboard is in test mode.  Not sure if this is stripe-node or stripe itself, or a configuration problem on my part.  Any help appreciated.

Calling 

```
Stripe.charges.create({ amount: 1000, customer: "cus_69gQ99ucXXrHbc", application_fee: 500, currency: "usd", destination: 'acct_15xOn0C1TnZvCUul'});
```
Results in a successful charge.

Calling 
```
Stripe.charges.create({ amount: 1000, customer: "cus_69gQ99ucXXrHbc", application_fee: 500, currency: "usd", destination: "acct_15xOn0C1TnZvCUul"},{ idempotency_key: "123"});
```
Results in `Unhandled rejection Error: Must provide source or customer.`

**Comment by matthewarkin** [comment]
@jimmiebtlr I'm guesing you already used the key "123" for a failed request so you're getting the response from that request. That said, I'd email support@stripe.com and they can look into the specifics

**Comment by jimmiebtlr** [comment]
Ok, thanks.

**Comment by Cauldrath** [comment]
This appears to be a legitimate issue.  When making a request with an idempotency_key set, the request to the Stripe API contains an empty body.  This is because when it is generating the data for the body, it runs this function:
https://github.com/stripe/stripe-node/blob/8385c41f49e3b13469735dbafc86ff7b1dd441b2/lib/utils.js#L64
Which checks for certain keys (including idempotency_key) to remove here:
https://github.com/stripe/stripe-node/blob/8385c41f49e3b13469735dbafc86ff7b1dd441b2/lib/utils.js#L16

It looks like the intention of this function is to remove idempotency_key from the request body, but instead it prevents any keys from being included at all, so an empty object is returned.

**Comment by Cauldrath** [comment]
Nevermind, I was including the idempotency_key in the first object instead of making a second object that contains the key.  I'm just going to leave my stupidity here in case anyone else runs into the same issue.

``Stripe.charges.create({ amount: 1000, customer: "cus_69gQ99ucXXrHbc", application_fee: 500, currency: "usd", destination: "acct_15xOn0C1TnZvCUul", idempotency_key: "123"});``
vs
``Stripe.charges.create({ amount: 1000, customer: "cus_69gQ99ucXXrHbc", application_fee: 500, currency: "usd", destination: "acct_15xOn0C1TnZvCUul"},{ idempotency_key: "123"});``

**Comment by matthewarkin** [comment]
@cauldrath I wonder if you're seeing what I saw in #179, all the api calls support an options argument to be included. The options argument is what should have things like the stripe account header, api key override, indempotency tokens and any additional headers. If you were to include one of these options in the actual request body than that would cause issues as stripe doesn't know if it's a body or options. I can double check this in a bit though
