### ISSUE TITLE
Regression: Checkout.sessions.create return object missing payment_intent (v11 works)

### ISSUE THREAD

**Issue by kftsehk** [stripe/stripe-node#1766]
### Describe the bug

`stripeClient.checkout.sessions.create(..)` returns `payment_intent: null` while it has a value in v11

### To Reproduce

Call checkout session api using payment mod, returns a session

```js
{
  id: 'cs_test_123456',
  object: 'checkout.session',
  // ...
  mode: 'payment',
  payment_intent: null
}
```

### Expected behavior

should return
```js
{
  id: 'cs_test_123456',
  object: 'checkout.session',
  // ...
  mode: 'payment',
  payment_intent: "pi_111111",
}
```

### Code snippets

```JavaScript
import stripe from 'stripe';

const { STRIPE_API_SECRET_KEY } = process.env;

const stripeClient = stripe(STRIPE_API_SECRET_KEY);

export const handler = async (event) => {
  const session = await stripeClient.checkout.sessions.create({
     // ....
  });
  
  console.log(session); // missing session.payment_intent
}
```

### OS

AWS Lambda Runtime

### Node version

v18

### Library version

stripe-node v12.1.1

### API version

 2022-11-15

**Comment by remi-stripe** [comment]
@kftsehk The latest version of stripe-node (v12.0.0) introduced what we call "API version pinning". This is documented in details in the wiki [here](https://github.com/stripe/stripe-node/wiki/Migration-guide-for-v12) but in summary it means all API requests the library makes will use the latest API version `2022-11-15` by default unless your code specifically overrides that version to match what you would expect.

Back in the API version [2022-08-01](https://stripe.com/docs/upgrades#2022-08-01) we made a change to the API:
> A PaymentIntent is no longer created during Checkout Session creation in payment mode. Instead, a PaymentIntent will be created when the Session is confirmed.

What this means is that any Session created with that API version or a more recent one (like the default in stripe-node v12.0.0) will not have `payment_intent` set anymore. This paves the way to future improvements such as Checkout Sessions where no payment is required after a 100% coupon for example.

Since you upgraded to v12.0.0 you need to make sure that your code is compatible with the latest API version. Alternatively, you can override the version to what your current code expects.
