### ISSUE TITLE
Allow specifying timestamp in webhook event signature verification

### ISSUE THREAD

**Issue by innermatrix** [stripe/stripe-node#1778]
### Is your feature request related to a problem? Please describe.

I am using the Stripe node API in a setting in which inbound events are placed in a queue before being processed by my code. As a result, there is a variable delay between when the webhook event is sent by Stripe and when it reaches my code. The only way to deal with this right now is to either increase tolerance in the call to `constructEvent` or to implement my own verification. 

### Describe the solution you'd like

I would prefer if `constructEvent` had an optional parameter that is the timestamp against which the webhook event timestamp will be compared. (Currently it always uses `now()` for comparison.) This would allow me to pass in the timestamp of when my queueing system received the message (rather than the time when I am processing the message). 

### Describe alternatives you've considered

Writing my own signature verification

**Comment by richardm-stripe** [comment]
Hello @innermatrix, thanks for the feature request. I've implemented this in #1782. I'll have the team take a look and if all is well we should be able to get this out in our Thursday release.

Just to kind of think out loud about the security implications of this: the purpose of verifying timestamps with a tolerance is to prevent a "replay" attack, where an attacker takes a message that was sent to your systems by Stripe, and sends a copy of that message again at a later time when the message has a different meaning. So, in order to keep your system secure you need to make sure that messaging from your queuing system to your application with stripe-node happens through a private channel and/or can't be spoofed, otherwise replay attacks would be possible.

**Comment by innermatrix** [comment]
@richardm-stripe Yup, understood re replay attacks; I am putting trust in the security of the timestamps in the queueing subsystem. Thanks!

**Comment by richardm-stripe** [comment]
Released in https://github.com/stripe/stripe-node/releases/tag/v12.4.0
