### ISSUE TITLE
Wrong type definition for create external account

### ISSUE THREAD

**Issue by Amirhossein-Haghpanah** [stripe/stripe-node#1784]
### Describe the bug

`external_account` property type inside `ExternalAccountCreateParams` is set to be `string` but it needs to be `string | <object with type of new external account>` just like how it is supported already in `AccountCreateParams` under `external_account`. 

Currently it is not possible to simply create an external account with object type and attach it to the account by id.

https://github.com/stripe/stripe-node/blob/e7800b3d5e689e23fece91f89f727af24ddf32a4/types/AccountsResource.d.ts#L2482

### To Reproduce

1. Create an account
2. Create an external account with details and attach to above account

### Expected behavior

1. Create account
2. Create an external account with details and attach to above account

### Code snippets

```JavaScript
const input: Stripe.ExternalAccountCreateParams = {
    default_for_currency: true,
    external_account: {
      object: "bank_account",
      account_holder_name: params.holderName,
      account_number: params.ibanNumber,
      account_holder_type: "individual",
      country: "DK",
      currency: "DKK",
    }
  };
  const externalAccount = await stripe.accounts.createExternalAccount(
    params.id,
    input
  );
```

### OS

macOS

### Node version

v19.5.0

### Library version

^11.1.0

### API version

2022-11-15

**Comment by richardm-stripe** [comment]
Hello @Amirhossein-Haghpanah, thanks for writing in.

The Typescript type here is by design, see https://github.com/stripe/stripe-node/issues/1181. Essentially, we strongly discourage passing raw details here. For most use cases, the user should create a token client-side and pass that instead.

If you really do need to handle raw details on your server, you can use `// @ts-ignore` or `as any` to suppress the Typescript error. 

Sorry if this is extra friction for you. Because raw payment details are so sensitive, we want to do as much as we can to prevent users who don't absolutely need to from unwittingly handling them directly.
