### ISSUE TITLE
Allow subscriptions.list to search specific customers

### ISSUE THREAD

**Issue by connerleverett** [stripe/stripe-node#1791]
### Is your feature request related to a problem? Please describe.

If we need to get the subscriptions for multiple users we need to call `subscriptions.list` multiple times, each with their own `customer` property. We could call `subscriptions.list` without a `customer` and then filter down the list, but that call is expensive as we have many customers. 

### Describe the solution you'd like

It would be great if `subscriptions.list` took a `customers` argument where you could pass an array of customer ids so only one call would be made. The current argument `customer` could also be overloaded to be `string | string[]` which would also solve the problem.

### Describe alternatives you've considered

Alternatively `subscriptions.search` could take `customers` as a query which again would be a list of customer ids.

### Additional context

Thanks in advance!

**Comment by remi-stripe** [comment]
Hey @connerleverett! Github issues are limited to bugs and feature requests with the stripe-node library itself. What you are asking here is more an API feature request which would need to be reported to our support team instead here: <https://support.stripe.com/contact/email>. I'll flag to the product team internally but I'd recommend that you report it to so that we can track this.

Unfortunately, this is unlikely to ship as a feature in the near future. We don't plan to support multiple ids in List APIs as it's something we experimented with before but it doesn't scale well. The Search API could work if we add support for the `customer` filter in the future which you could combine with `OR` but it's also not something we'll add soon at least.

**Comment by connerleverett** [comment]
Thanks for the quick response and all the info @remi-stripe ! I'll shoot off an email to the support team so it's tracked.
