### ISSUE TITLE
Subscription create is missing the type for the discounts field

### ISSUE THREAD

**Issue by FarazPatankar** [stripe/stripe-node#1798]
### Describe the bug

We want to attach multiple coupons to the subscriptions we create for our customers. When I try to use the `discounts` property listed [here](https://stripe.com/docs/api/subscriptions/create#create_subscription-discounts), TypeScript tells me the property does not exist in the `SubscriptionCreateParams` type.

Note: Ignoring the TypeScript error and passing the property anyway just works.

### To Reproduce

1. Get a Stripe client `const stripe = new Stripe(...)`
2. Call the `stripe.subscriptions.create` function and try passing the `discounts` field to it
3. You should now see the below error from TypeScript.

```
Argument of type '{ customer: string; discounts: SubscriptionCreateDiscount[]; items: ({ price: string; } | { price: string; quantity: number; })[]; billing_cycle_anchor: number; off_session: true; expand: string[]; }' is not assignable to parameter of type 'SubscriptionCreateParams'.
  Object literal may only specify known properties, and 'discounts' does not exist in type 'SubscriptionCreateParams'.
```

### Expected behavior

`SubscriptionCreateParams` should include the type for the `discounts` property.

### OS

macOS

### Node version

Node v16.x

### Library version

stripe-node v12.6.0

### API version

2020-08-27

**Comment by FarazPatankar** [comment]
This should probably have the `type definition` label but I don't think I am allowed to add it.

**Comment by remi-stripe** [comment]
Hey @FarazPatankar, thanks a lot for the detailed bug report! Our Subscriptions API does not yet support adding multiple Coupons/Discounts to one Subscription publicly. If you look at the API reference without being logged into your Stripe account, you wouldn't see a `discounts` parameter.
You are likely associated with a Stripe account that is in a beta for this as we have been working on support for it for a while. Our client libraries/SDKs like stripe-node only have the types for what is officially public for everyone in our API which is why you are not seeing `discounts` in your types.

In the future, when this ships publicly for everyone, you will see the types in the library as expected!

**Comment by FarazPatankar** [comment]
Is there already a type for what an item in the `discounts` array would look like that I can copy? I've currently manually set it to the type below:

```ts
interface SubscriptionCreateDiscount {
  coupon: string;
}
```

**Comment by remi-stripe** [comment]
We don't have specific types for it yet as the feature hasn't been officially released yet so I don't have anything specific to share.

**Comment by FarazPatankar** [comment]
Understandable. Really appreciate the quick replies btw. I'll see if I can get support to help me out! 😄
