### ISSUE TITLE
`RefundCreateParams` has `currency` property but not accepted by backend

### ISSUE THREAD

**Issue by photz-insify** [stripe/stripe-node#1804]
### Describe the bug

The `RefundCreateParams` type suggests that a `currency` can be passed when creating a refund, but when I do that, I get the following error:
```
Uncaught StripeInvalidRequestError: Received unknown parameter: currency
    at Function.generate (/home/me/foo/node_modules/stripe/cjs/Error.js:10:20)
    at res.toJSON.then.Error_js_1.StripeAPIError.message (/home/me/node_modules/stripe/cjs/RequestSender.js:105:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'StripeInvalidRequestError',
  raw: {
    code: 'parameter_unknown',
    doc_url: 'https://stripe.com/docs/error-codes/parameter-unknown',
    message: 'Received unknown parameter: currency',
    param: 'currency',
    request_log_url: 'https://dashboard.stripe.com/test/logs/req_nZtApTZdp0RKJW?t=1685629385',
    type: 'invalid_request_error',
    headers: {

...
```

### To Reproduce

1. Create a charge 
2. Refund (part of) that charge: 
```
await stripe.refunds.create({ amount: 1,currency:'eur',charge: '<<charge ID>>'})
```

### Expected behavior

Either
* the `RefundCreateParams` type should be updated to remove the `currency` property
* the refund creation endpoint should accept the `currency` property

### OS

linux

### Node version

16.20.0

### Library version

12.6.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
Hey @photz-insify, sorry about the confusion here. This parameter is for a specific refund flow associated with refunding money from the Customer's cash balance. You can't choose the currency of a Refund associated with an existing Charge or PaymentIntent. Instead it'd be for [this flow](https://stripe.com/docs/payments/bank-transfers#refunds) specifically.

I'll flag internally so that we can improve the docs around this and the docstring in stripe-java but in your example code you should not pass `currency` at all.
