### ISSUE TITLE
retrieveUpcoming requires a subscription

### ISSUE THREAD

**Issue by kevinpagtakhan** [stripe/stripe-node#1843]
### Describe the bug

I'm retrieving an upcoming invoice using `retrieveUpcoming` API to get prorated cost for subscription items. The [docs](https://stripe.com/docs/api/invoices/upcoming?lang=node) says `customer` field is "required if subscription unset" and `subscription` field is optional and "if not provided, but a `subscription_items` is provided, you will preview creating a subscription with those items". So when sending a request to retrieve upcoming invoice, I am only providing `customer` and `subscription_items` fields but an error is returned with a message:

```
StripeInvalidRequestError: You cannot update a subscription item without a subscription.
```

### To Reproduce

See code snippet

### Expected behavior

Return a response with a "preview creating a subscription with those items".

### Code snippets

```JavaScript
const invoice = await stripe.invoices.retrieveUpcoming({
  customer: '...',
  subscription_items: [
    {
      id: '...',
      quantity: 1,
    }
  ],
});
```

### OS

macOS 13.1

### Node version

Node v18.13.0

### Library version

stripe-node v9.5.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
Hey @kevinpagtakhan! Github issues are limited to bugs with the stripe-node library itself. This is more an integration support question better directed at our support team instead: https://support.stripe.com/contact

To unblock you though, the `subscription` parameter is required in this specific case if you are trying to change existing SubscriptionItem(s) of an existing Subscription. It's only optional if you're trying to preview the first Invoice of a Subscription before it's even created. I hope this helps but if you have follow up questions, please contact our support team directly instead of replying on this issue!
