### ISSUE TITLE
Ability to set a name for and/or rename Payment Links

### ISSUE THREAD

**Issue by rockingskier** [stripe/stripe-node#1852]
### Is your feature request related to a problem? Please describe.

In my app, I generate a Payment Link for each customer.  This allows me to add metadata for their account and link the payment back to them.

In the Stripe Dashboard, I then end up with a lot of Payment Links, all with identical names and unique metadata.

I can manually go in and rename them, but that is a very manual job, copying some metadata into the Link name.

<img width="316" alt="Screenshot 2023-07-20 at 23 48 54" src="https://github.com/stripe/stripe-node/assets/681614/3521fe40-11f0-448e-a715-b3cf28941229">

### Describe the solution you'd like

When using the [create Payment Link API](https://stripe.com/docs/api/payment_links/payment_links/create), it would be amazing if a `name` could be provided instead of it being generated based on the `line_items` in the basket.

```
stripe.paymentLinks.create({
  line_items: [
    {
      price: 'price_11111111111', // Product One
      quantity: 1,
    },
  ],
  metadata: {
    customerName: 'Customer One',
    customerId: 1,
  },
})
```

<img width="431" alt="Screenshot 2023-07-20 at 23 48 59" src="https://github.com/stripe/stripe-node/assets/681614/c4ece20d-f930-4560-ac24-07cd31843d3e">

### Describe alternatives you've considered

Manually renaming Links...

### Additional context

I'm very new to Stripe, I could well be doing this all wrong :)

**Comment by remi-stripe** [comment]
@rockingskier Github issues should be limited to bugs or feature requests with the library itself. This is more a product feature and it should be reported to our support team instead [here](https://support.stripe.com/contact) so that they can track this as a feature request in the future. 

Usually, PaymentLinks are seen more as a "factory" to accept many payments. For example you sell a book for $20 and you share the URL with all your followers and some of them click the link to buy the book. It's less common to have a one-time use PaymentLink for one specific Customer usually which might be why you're hitting this. It's more common in this case to have your own payment page with a button for your customer and then you create a Checkout Session for them on demand based on what they are trying to buy instead.

Our support team can help you architecture this better if needed so make sure to reach out to them!

**Comment by rockingskier** [comment]
Thanks @remi-stripe, I'll have a look at Checkout Sessions and go from there.  Thank you.
