### ISSUE TITLE
Pay by Bank support

### ISSUE THREAD

**Issue by DrChrispoper** [stripe/stripe-node#1865]
### Describe the solution you'd like

https://stripe.com/docs/payments/pay-by-bank/accept-a-payment?platform=checkout#enable-pay-by-bank-as-a-payment-method

Shows the following usage.

```
const session = await stripe.checkout.sessions.create({
  payment_method_types: ['card', 'pay_by_bank'],
  payment_method_options: {
    pay_by_bank: {
      country: 'gb',
      locale: 'en-gb',
      statement_descriptor: 'merchant name',
    }
  },
  line_items: [{
    price_data: {
      // To accept `pay_by_bank`, all line items must have currency: gbp
      currency: 'gbp',
      product_data: {
        name: 'Blue bananas',
      },
      unit_amount: 2000,
    },
    quantity: 1,
  }],
  mode: 'payment',
  success_url: ['https://example.com/success'](https://example.com/success),
  cancel_url: ['https://example.com/cancel'](https://example.com/cancel),
});
```

`PaymentMethodType` is missing `pay_by_bank` and `payment_method_options` doesn't support `pay_by_bank` either.

**Comment by DrChrispoper** [comment]
I don't know if it's just types missing or some implementation. I could (try) have a look if someone points me in the right direction.

**Comment by remi-stripe** [comment]
@DrChrispoper This feature is in private beta and only accessible by people in the beta. That link you shared for example only works when logged into your Stripe account, if you try in incognito you will get a 404.
Our client libraries/SDKs do not directly support betas in the main trunk so that's why you don't see types for it. We do have a beta pipeline with beta features though only a subset are covered and we rarely add payment methods like this to it.
I'd recommend working with your point of contact at Stripe who gave you access to discuss this and they can look into potential improvements but for now the types will only be released once this feature becomes public for everyone.

If you have any follow up questions, working with your point of contact or our support team at https://support.stripe.com/contact is the best next step!

**Comment by anniel-stripe** [comment]
Hi @DrChrispoper ! Following up on this - as mentioned above, we have a separate beta version of the SDK. You can follow instructions in the [README's Beta SDKs section](https://github.com/stripe/stripe-node#beta-sdks) to install it. `pay_by_bank` was recently added in [v12.14.0-beta.1](https://github.com/stripe/stripe-node/releases/tag/v12.14.0-beta.1).

**Comment by DrChrispoper** [comment]
Thanks for explaining!
