### ISSUE TITLE
setting the stripe api version explicitly is not working

### ISSUE THREAD

**Issue by ka1r0** [stripe/stripe-node#1899]
### Describe the bug

to test the new stripe api version 2023-08-16 on our staging server in stripe test mode i tried to set it explicitly (code see below), but the configuration is not respected. all requests use the version 2022-11-15 which is set in the stripe dashboard. i confirmed this via stripe dashboards logs and a mitm proxy.

### To Reproduce

const Stripe = require('stripe')(Config.stripe.api.secret, { apiVersion: '2023-08-16' })

### Expected behavior

stripe api version used should be one set explicitly: 2023-08-16

### Code snippets

```JavaScript
const Stripe = require('stripe')(Config.stripe.api.secret, { apiVersion: 2023-08-16 })

console.log('Stripe._api', Stripe._api)

Stripe._api {
auth: 'Bearer XXXX',
host: 'api.stripe.com',
port: '443',
protocol: 'https',
basePath: '/v1/',
version: '2023-08-16',
timeout: 80000,
maxNetworkRetries: 1,
agent: null,
httpClient: NodeHttpClient { _agent: undefined },
dev: false,
stripeAccount: null
}

694177017401 POST 127.0.0.1 /api/webhooks/stripe 200 {
  "id": "evt_1No428HGSlvYmTO2noHbiNag",
  "object": "event",
  "api_version": "2022-11-15",
  "created": 1694177016,
...
}
```

### OS

Debian GNU/Linux 10 (buster)

### Node version

node:18-alpine

### Library version

13.5.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@ka1r0 When you force an API version like this it applies to the API request you make to our API. For example calling the Create Customer [API](https://stripe.com/docs/api/customers/create) would use that API version as expected.

This does **not** apply to the Events that are being generated as a result of that API request or any other action. Events are always generated based on either the API version explicitly set on your WebhookEndpoint if any, which can control via the `api_version` [parameter](https://stripe.com/docs/api/webhook_endpoints/create#create_webhook_endpoint-api_version) and otherwise uses your account's default API version as configured in the Dashboard.

There are many Events that are created separately from any specific API Request you made. If we used the API version that was used to create the object originally, it'd be really hard for integrations to handle older objects or parts of their codebase that have been built with different API versions in mind. That's one of the reasons (amongst many others) why the system was designed this way so that you can decouple the two integration paths

The way you framed your question makes me think you are mixing up the two concepts and are expecting your Event to have the same API version that you pass in the request which wouldn't be the case.

If you are trying to migrate to the latest API version, make sure to create a new/separate WebhookEndpoint with the right API version set on creation and you should then see the Events come in with the expected API version.

**Comment by ka1r0** [comment]
Thanks for your explanation. I now realize that in my case I need to create a webhook with the API version I want to test.
