### ISSUE TITLE
Timeline for node 12 sunsetting

### ISSUE THREAD

**Issue by bernzjh** [stripe/stripe-node#1908]
### Is your feature request related to a problem? Please describe.

Not a problem yet, but would like some guidance on when this package will drop node 12 support (you seem to do it ever few major version releases.)

### Describe the solution you'd like

An idea of the timeline for node 12 being phased out if one exists.

**Comment by bernzjh** [comment]
Thank you for the quick response. That would be immensely considerate and
helpful.

**Comment by anniel-stripe** [comment]
Hi @bernzjh! Discussed with the team, and unfortunately we can't offer a concrete timeline at the moment. In general, we start considering dropping support for a runtime version when there is a forcing factor like our dependencies not supporting it, or a higher version enables a feature we want to use. That is not the case with Node 12 just yet.

I'm going to close out this issue since the answer to your question is "no timeline at the moment." Feel free to reopen if there's a problem you have that would be addressed by the library dropping Node 12 support.

**Comment by bernzjh** [comment]
It is not currently causing any particular issues, but we are reviewing
some of our older codebases that are in need of updating, and are trying to
create a timeline for prioritizing them.

**Comment by bernzjh** [comment]
Thank you for your prompt response on this issue. It has helped immensely.
