### ISSUE TITLE
need a v13+ beta released that includes `CustomerSession` 

### ISSUE THREAD

**Issue by mesqueeb** [stripe/stripe-node#1922]
### Is your feature request related to a problem? Please describe.

We rely on the pricing tables UI where our customers choose a plan from. We need to be able to pass existing customers, so rely on the `CustomerSession` record from https://github.com/stripe/stripe-node/releases/tag/v12.11.0-beta.1

See docs:
![image](https://github.com/stripe/stripe-node/assets/3253920/815152f9-9d96-473c-bf25-ffa02ade6e98)

### Describe the solution you'd like

The `CustomerSession` from https://github.com/stripe/stripe-node/releases/tag/v12.11.0-beta.1 needs to be released in a beta for v13+ as well. Because we can't upgrade past v13 if none of the beta versions include this `CustomerSession`  type...

**Comment by remi-stripe** [comment]
@mesqueeb That API is present in all beta version since. If you look at the code on the beta branch, you can see [CustomerSessions.ts](https://github.com/stripe/stripe-node/blob/beta/src/resources/CustomerSessions.ts) as expected. If you download the latest beta [v13.11.0-beta.1](https://github.com/stripe/stripe-node/releases/tag/v13.11.0-beta.1) you can also quickly confirm the source has it as expected.

I'm going to close as it doesn't look like a feature request and is more integration support shaped. You can talk to our support team if you need further help: https://support.stripe.com/contact

**Comment by mesqueeb** [comment]
@remi-stripe thanks so much! :tada:
