### ISSUE TITLE
Issues with very old user IDs

### ISSUE THREAD

**Issue by stefanosala** [stripe/stripe-node#194]
Hi folks,
we're on our way to publish our Application that uses Connect.

We're having some troubles testing it with some users because of their user IDs, which are in the form of 32 alpha-numerical characters.

The problem is that they are interpreted as authentication keys and not user ids when doing calls such as `accounts.retrieve`: https://github.com/stripe/stripe-node/blob/master/lib/resources/Accounts.js#L35

Is there a way to force those calls to treat those user ids correctly not as authentication keys?

Thanks!

**Comment by matthewarkin** [comment]
Well I thought I found a workaround but I believe that work around is abusing a bug in the API so I've pinged some folks to investigate that bug and hopefully once that comes back I can think of a proper workaround / fix, or maybe a Stripe will.

I have a very horrible disgusting work around https://github.com/stripe/stripe-node/commit/2473296a5bd38664be375cc93cb15a39831d9485, basically you'd send an object with the key "id" as the first parameter instead of passing a string.

**Comment by matthewarkin** [comment]
@bkrausz any thoughts on a decent way to handle this? 
My initial thought would be to deprecate passing api key as the first argument and require that the first parameter be an account id or an empty string (to access your own account). 

So
```javascript
 // retrieve a connected account
stripe.Accounts.retrieve("account id", "api key" || {options args}, callback)
 // retrieve self  account / account for api key / stripe_account
stripe.Accounts.retrieve("", "api key" || {options args}, callback) 
```

or add a `retrieveSelf` function that would take no urlParam, just the optional options argument and callback. 

Can't say I'm a *huge* fan of either method.

**Comment by bkrausz** [comment]
Sounds like we should check for a 2nd hash-or-string param, which would indicate that the first string is an account ID. Then you could pass `stripe.Accounts.retrieve("account id", {}, callback)`. Does that sound like it would all permutations of issues here?

**Comment by matthewarkin** [comment]
yeah, so that's essentially my first option and if the first param is an empty string / null the library would request `/account`

**Comment by stefanosala** [comment]
Thanks for the feedback guys, please keep us posted as it seems it will be a BC with the current version.

**Comment by matthewarkin** [comment]
Have a PR open that should handle this in the most backwards compatible way that I could thing of but its still a breaking change.

If the first argument to account.retrieve is a string, that string is assumed to be the account id instead of the library trying to make an educated guess. You can pass null as the first parameter if you want to just pass an api key, or even more preferred would be to use an options object with the api_key set. Eg: `stripe.account.retreive({api_key: "access token"}).

**Comment by kyleconroy** [comment]
4.0.0 has shipped
