### ISSUE TITLE
Permission denied when passing unified_accounts_beta=v1 header

### ISSUE THREAD

**Issue by ljrahn** [stripe/stripe-node#2004]
### Describe the bug

I have been in contact with stripe support back and forth a lot since _December 7th_ and I haven't been able to get a straight answer as to why I can't integrate what is outlined in the first link of the connect documentation (https://stripe.com/docs/connect/customized-integration-guide). I am halted when I try to pass the `unified_accounts_beta=v1` header and make an API call, i receive the outlined error. I tried to get access to the beta by contacting stripe support, but there was a long line of confusion, elevation to "internal specialized teams", and inconsistent responses that didn't make sense almost as if they were unaware of the provided documentation, and not capable of reading it. To me it seems that with the new beta header, the documentation implies the removal of the account type, and the ability to use embedded connect onboarding, in conjunction with the stripe dashboard. This was not previously possible with any of the account types (express has hosted onboarding pages, and express dashboard, and custom has entire integration yourself via API, or the use of embedded components, ie. no stripe dashboard).

I am raising an issue, because I don't know where else to get my answer (even though I understand this is not a bug in the library itself), and this has become a fairly time sensitive issue. If you can point me in the right direction, it would be greatly appreciated!

### To Reproduce

1. Define the stripe instance with `apiVersion: "2023-10-16; unified_accounts_beta=v1"`
2. Make any API call.

### Expected behavior

I expect to be able to follow the documentation link provided to be able to use embedded connect onboarding, and the stripe dashboard.

### Code snippets

```JavaScript
const stripe = new Stripe(stripeSecretKey.value(), {
  // @ts-ignore
  apiVersion: "2023-10-16; unified_accounts_beta=v1",
});

Error: Invalid Stripe API version: 2023-10-16; unified_accounts_beta=v1. You do not have permission to pass this beta header: unified_accounts_beta. If you have any questions, we can help at https://support.stripe.com/.
```

### OS

macOS

### Node version

v19.2.0

### Library version

^14.8.0-beta.1

### API version

2023-10-16; unified_accounts_beta=v1

**Comment by remi-stripe** [comment]
@ljrahn I'm really sorry but we can't help with this here. Github issues are limited to bugs with the SDK itself. Your question is an integration support question that only our support team can help fix. 99% of the time, the issue is simply that you are using the API key from account A but it doesn't have access to that beta/secrete feature. You likely have multiple accounts and the wrong one got the feature enabled. 

Just clarifying that since the beta started we have shipped multiple features publicly. Our Connect Embedded product is live now and documented [here](https://stripe.com/docs/connect/get-started-connect-embedded-components) with multiple embeddable UI components such as showing Payouts or Payments breakdown. You don't need that "Unified Accounts" beta to use it at the very least. But if you do need that beta then you have to work with our support team to give you access first. And we don't give access to most people yet, there's a wait list.

Sorry I can't help more, please reach out to our support team again at https://support.stripe.com/contact and feel free to mention this Github issue an that you spoke to me.
