### ISSUE TITLE
[Feature request] built-in retry when `lock_timeout` error for `stripe.customers.retrieve()`

### ISSUE THREAD

**Issue by GorvGoyl** [stripe/stripe-node#2056]
### Is your feature request related to a problem? Please describe.

sometimes i get the below error and it would be nice if the library could take care of it (with exponential backoff) instead of devs catching the error, checking the code, and then trying again.

```js
{
  "error": {
    "code": "lock_timeout",
    "doc_url": "https://stripe.com/docs/error-codes/lock-timeout",
    "message": "This object cannot be accessed right now because another API request or Stripe process is currently accessing it. If you see this error intermittently, retry the request. If you see this error frequently and are making multiple concurrent requests to a single object, make your requests serially or at a lower rate.",
    "request_log_url": "https://dashboard.stripe.com/logs/req_o73536",
    "type": "invalid_request_error"
  }
}
```

### Describe the solution you'd like

would be nice if the library could take care of it (with exponential backoff)

**Comment by richardm-stripe** [comment]
Hello @GorvGoyl, thanks for writing in.

The library has a setting `max_network_retries` (see [README.md](https://github.com/stripe/stripe-node?tab=readme-ov-file#initialize-with-config-object)) that should enable retries with exponential backoff on requests that are eligible to be retried.

The [official Stripe docs](https://docs.stripe.com/rate-limits#object-lock-timeouts) seem to say

> the automatic retry mechanisms built into Stripe’s [client libraries](https://docs.stripe.com/docs/libraries) retry 429s 

caused by lock timeouts so based on that, if you have set `max_network_retries` to something greater than 0 and are not seeing these requests being retried, then there is something wrong either with the library or the docs. Though 429 status codes are [deliberately not retried by the library](https://github.com/stripe/stripe-node/issues/1110) in other circumstances, like rate limiting.

Can you confirm what your `max_network_retries` setting is, and also -- are you able to provide the HTTP status code of the response and whether or not the `Stripe-Should-Retry` header is present on the response?

**Comment by GorvGoyl** [comment]
Thank you for your detailed response, grateful for that! I didn't know that the stripe library provides a way to do that (I should've checked that before raising the issue).  I've implemented that approach and will reach out if I still face the issue. closing the issue for now.
