### ISSUE TITLE
No signatures found matching the expected signature for payload.

### ISSUE THREAD

**Issue by zellwk** [stripe/stripe-node#2078]
### Describe the bug

I'm using Astro to construct a webhook for Stripe, following the Deno example here because it uses the same `request` object. 

But I'm getting an error that says "No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? "

### To Reproduce

1. Send a POST request from a webhook 
2. Try to use `constructEventAsync` or `constructEvent`. 
3. Get error

### Expected behavior

Expected to get the event from `stripe.webhooks.constructEventAsync` or `stripe.webhooks.constructEvent`. 

[Deno example](https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/deno/main.ts#L19-L30)

```js
async function handler(request) {
  const signature = request.headers.get('Stripe-Signature');

  const body = await request.text();
  let event;
  try {
    event = await stripe.webhooks.constructEventAsync(
      body, signature, Deno.env.get('STRIPE_WEBHOOK_SECRET'), undefined
    );
  } catch (err) {
    console.log(`❌ Error message: ${err.message}`);
    return new Response(err.message, {status: 400});
  }
```

What I used (Astro)

```js
export async function POST({ request }) {
  const sig = request.headers.get('Stripe-Signature')
  const body = await request.text()

  let event

  try {
    event = await stripe.webhooks.constructEventAsync(
      body,
      sig,
      WEBHOOK_SECRET,
      undefined
    )
    console.log(`Event Type: ${event.type}`)
  } catch (err) {
    console.log(err.raw.message)
  }
 
```

### OS

macOs

### Node version

21.7.1

### Library version

15.4.0

### API version

2024-04-10

**Comment by remi-stripe** [comment]
@zellwk This is more an integration support question better directed at our support team: https://support.stripe.com/contact

Overall with Node.js and equivalent, it's unfortunately really common to get that error. It's often due to your framework/stack trying to be helpful by noticing the data you received is in JSON and parsing for you. You need to make sure that what you pass to `constructEvent()` is the exact raw payload as a string that we sent you, not deserialized JSON, a data buffer or a re-serialized string from deserialized JSON. You can look at https://github.com/stripe/stripe-node/issues/356 which is an issue with dozens of potential solutions depending on your setup or environment
Also triple and quadruple check that you use the right WebhookEndpoint secret `whsec_123`. It's common to mix them up or not realize that the CLI has its own secret.
