### ISSUE TITLE
Support for `footer` in `invoice_settings`

### ISSUE THREAD

**Issue by andreialecu** [stripe/stripe-node#2091]
### Is your feature request related to a problem? Please describe.

I'm not sure if this is a bug in this library or lack of support in the underlying API, but there doesn't seem to be a way to programatically define the footer for invoices that are sent by subscriptions.

This is possible to do via the web admin:
![CleanShot 2024-05-17 at 12 00 49@2x](https://github.com/stripe/stripe-node/assets/697707/aa1ba250-7408-49e1-84f2-2a25bf0114a2)

### Describe the solution you'd like

```ts
 await this.stripeUtilsService.stripe.subscriptionSchedules.create({
          default_settings: {
            collection_method: 'send_invoice',
            invoice_settings: {
              days_until_due: 7,
              footer: 'test123', // this should be possible
            } ,
          },
```

### Describe alternatives you've considered

I suppose it may be possible to look for the pending invoice and update it? 

Not clear how to do this otherwise.

### Additional context

The documentation doesn't specify any way to set up a footer: https://docs.stripe.com/api/subscription_schedules/create

Same for other fields that may be missing. Also not just `subscriptionSchedules` are affected, but `subscriptions` too.

**Comment by andreialecu** [comment]
I believe this actually exists just that it isn't documented anywhere. 

I inspected the POST request that the web admin does to update the field, and I see that it does indeed pass a `footer` in `invoice_settings`.

**Comment by remi-stripe** [comment]
Hello! This feature is currently only available to the Dashboard and can't be used in the API which is why you don't see it documented. It's on our list of feature requests but hasn't made it up to the top of the list just yet.

I'm going to close this issue as your ask is more an API feature request and is better directed to our support team who can help track the asks. You can contact them here: https://support.stripe.com/contact
