### ISSUE TITLE
PaymentIntent interafce does not have charges object in it even tho it is sent from stripe webhook on payment_intent.succeeded event

### ISSUE THREAD

**Issue by Hackerokuz** [stripe/stripe-node#2112]
### Describe the bug

PaymentIntent interafce does not have charges object in it even tho it is sent from stripe webhook on payment_intent.succeeded event.

### To Reproduce

Check if type Stripe.PaymentIntentSucceededEvent['data']['object'] for charges type.
charges object does not exist even tho it is sent from stripe servers.

### Expected behavior

Stripe.PaymentIntentSucceededEvent['data']['object'] should contain charges object as it is sent in the Payment Intent Succeeded Event.

### OS

Windows 10

### Node version

Node v20.13.1

### Library version

stripe 14.25.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
The `charges` property on PaymentIntent is deprecated and it was removed in the API version [2022-11-15](https://docs.stripe.com/upgrades#2022-11-15) where we say
> The charges property on [PaymentIntent](https://docs.stripe.com/api/payment_intents/object) has been removed. You can use the latest_charge property instead.

You likely have an old integration and your Stripe account has a default API version older than this so you are still getting the `charges` property on those (otherwise it'd be breaking a lot of existing integration). The types in the stripe-node SDK match the latest API version which is why they have `latest_charge` and not `charges` anymore.

If you have any follow up questions, please work directly with our support team for 1:1 integration support help: https://support.stripe.com/contact

**Comment by aaronhudon-pq** [comment]
@remi-stripe doesn't this defeat the purpose of reducing the amount of requests we make to the API?  I just got stung with this deprecation

**Comment by remi-stripe** [comment]
Sure it defeats that purpose but it leads to improved latency for other requests, it's all a balance really and this has drastically improved the overall latency of those APIs as many developers don't need the full Charge object in that flow, or can listen to `charge.succeeded` for example. But we definitely know that in some cases, possibly like yours, it does lead to an extra request in your webhook handler.

**Comment by aaronhudon-pq** [comment]
@remi-stripe breaking an API is bad.  If there was improved throughput to be had, why not just make a `payment_intent.succeeded_v2` event and alert developers of this thinned out version?
