### ISSUE TITLE
Stripe Connect Documentation

### ISSUE THREAD

**Issue by imns** [stripe/stripe-node#212]
I would absolutely love if you could expand on the Stripe Connect documentation you have here https://github.com/stripe/stripe-node/wiki/Using-Stripe-Connect-with-node.js

For instance, I am currently trying to retrieve all of the charges for a connected account

```JS
stripe.charges.list(accessToken, function(err, charges) { ... });
```

Where `accessToken` is the connected accounts: account id, publishable key and secret key and nothing seems to work.  I've tried passing an empty object or `{limit: 3}` before the `accessToken`, but that doesn't seem to work either.  

I should also note that I'm using managed accounts.

**Comment by remistr** [comment]
Hey @imns,

First off, I'd recommend moving to the `Stripe-Account` [header](https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header) feature instead of using the access token as this is the proper way to make API calls on behalf of connected accounts now.

Then, when listing charges on the connected account, your could should be:
```
// Set the platform's key
var stripe = require('stripe')("sk_test_XYZ");

stripe.charges.list(
  {
    limit: 2
  },
  { stripe_account: "acct_XYZ"},
  function(err, charges) {
    console.log("Charges : ", JSON.stringify(charges));
  }
);
```

Now this only works if you're on a recent API version, specifically [2015-09-23](https://stripe.com/docs/upgrades#2015-09-23) or a more recent one as this is something we changed:

>The Charges endpoint previously returned only card charges. Charges now returns all charges, such as card charges and bank account charges. See the endpoint’s documentation for information on filtering by charge source type. The deprecated offset parameter is now only supported when filtering by charge source type. To simultaneously paginate charges from all sources, see https://stripe.com/docs/api#pagination.

If you're on an earlier version you need to pass `source[object]=all` as documented. This is due to the fact that charges created via [destination](https://stripe.com/docs/connect/payments-fees#charging-through-the-platform) create a Payment `py_XYZ` on the connected account and not a Charge. Your code would become:

```
// Set the platform's key
var stripe = require('stripe')("sk_test_XYZ");

stripe.charges.list(
  {
    limit: 2,
    source: { object: "all" }
  },
  { stripe_account: "acct_XYZ"},
  function(err, charges) {
    console.log("Charges : ", JSON.stringify(charges));
  }
);
```

**Comment by imns** [comment]
Thanks for the reply, how do I go about adding the `Stripe-Account header ` via the node api?  Will adding `{ stripe_account: "acct_XYZ"}` do it or is there something additional that needs set?

**Comment by remistr** [comment]
@imns so yes that's what `stripe_account` in the code I shared means here. It automatically sets the `Stripe-Account` header for you in the request.

**Comment by imns** [comment]
Awesome, thanks for the speedy help @remistr.
