### ISSUE TITLE
List Prices not reporting active status properly

### ISSUE THREAD

**Issue by RavenHursT** [stripe/stripe-node#2131]
### Describe the bug

When I make a request to get a list of prices using `stripe.prices.list({active: true})`, I get a bunch of prices on products that I just archived.

When I make a subsequent attempt to create a checkout session against one of these products' prices, I get an error.

<img width="321" alt="image" src="https://github.com/stripe/stripe-node/assets/496983/a5783ec7-c0b9-40cb-b5c0-72dc965bdd2a">
<img width="594" alt="image" src="https://github.com/stripe/stripe-node/assets/496983/55ea7a4b-423a-4d44-8950-ad58d8fc6c68">

### To Reproduce

Set some products to be archived.

Call for a listing of prices, filtered by `active: true`

attempt to create a checkout session against one of the prices that are returned, and marked as `active`, when in fact they are not.

### Expected behavior

`{active: true}` should only return product prices that have _not_ been archived

### OS

macOs

### Node version

v20.14.0

### Library version

stripe@15.8.0

### API version

2024-06-20

**Comment by remi-stripe** [comment]
@RavenHursT It's possible for the Price to have `active: true` but the underlying Product to have `active: false` which is what's happening here. I do agree it's not the clearest but that's why the List Prices API behaves this way overall.
One thing we could consider would be to move all Prices as `active: false` after you switch the Product but then when you reactivate the Product you'd have to remember to flip back all the Prices which wouldn't be great.

I hope this clarifies the behaviour overall but if you have any follow up questions I'd recommend reaching out to our support team instead for 1:1 support: https://support.stripe.com/contact
