### ISSUE TITLE
Thrown error should be in callback

### ISSUE THREAD

**Issue by Nijikokun** [stripe/stripe-node#215]
Un-documented thrown error kept taking down my application:

https://github.com/stripe/stripe-node/blob/master/lib/StripeMethod.js#L45

**Comment by brandur** [comment]
Hi @Nijikokun, sorry about the trouble here!

So this exception is a usage error that occurs if an API call method is misused by not passing enough arguments or by passing a `null` when we needed a value. Ideally you'll be able to avoid it at runtime completely by having a test suite that's adequate enough to reasonably exercise your code and/or by performing some basic input checks to make sure that you're not passing a `null` inappropriately. Obviously this is easier said than done, but you should be able to get yourself into a place where you never see this error unexpectedly.

I'm going to close this issue out for now, but of course let us know if you have anymore comments/questions on the problem. Thanks!

**Comment by Nijikokun** [comment]
It should at least be documented.

**Comment by brandur** [comment]
> Finding the callback would be as simple as checking for an argument of type function.

@Nijikokun I'm still a little hesitant to pass it back through the standard runtime paths because this is the type of error that indicates that something is very wrong in the user code, and by extension it should be made very difficult to ignore or not handle. If this was a compiled language, this would be the sort of problem that the compiler would not allow through to run time.

By fair enough. I don't have great Node familiarity, so if you have other specific ideas on how to improve things I'd be happy to take a look. When you talk about documentation, do you just mean the function's documentation or something else?

**Comment by matthewarkin** [comment]
@brandur I get why it makes sense that this is a thrown exception, though the Errors api docs doesn't state anywhere that the node.js sdk will throw an error. One thing for me is that the handling for how invalid requests are handled are different based on if the check happens client-side or server-side, so creating a charge with a null card would return an invalid request error in the callback but trying to update a customer with a null id would instead throw an error. Who is to say that we shouldn't have logic in the create charge method that checks that `amount != null && (customer!= null || source != null)`? Both these instances are invalid requests but they're handled differently.

And per Joyent's Node docs (not necessarily saying these are best practices)
>The general rule is that a function may deliver operational errors synchronously (e.g., by throwing) or asynchronously (by passing them to a callback or emitting error on an EventEmitter), but it should not do both. This way, a user can handle errors by either handling them in the callback or using try/catch, but they never need to do both. Which one they use depends on what how the function delivers its errors, and that should be specified with its documentation.

Thus we have a function that is expected to async which can fail either synchronously through a thrown error, or asynchronously through the callback.

**Comment by brandur** [comment]
@matthewarkin Fair enough. I guess I was trying to say that this sort of more basic argument error is an entirely different class that shouldn't even be valid enough to be sent to a server, but I understand the argument that it does effectively take a subset of input validation (i.e. checks on null parameters) and put it client-side.

The documentation you posted from Joyent also seems like quite a reasonable policy.

Okay, I have one change suggestion that I wanted to pitch to you guys. I suspect that the major complaint here is not so much a problem on mis-use of an API function (i.e. not passing enough parameters) because that kind of thing will be caught right away in development and/or tests, but rather the implicit pseudo-validation that it might do on parameters. So for example, if you're using the function correctly, but then pass a parameter that's `null` in production because of some unexpected user input.

What we could do is change the exception check so that it's only thrown if an accessed element was `undefined` instead of `null`. This would mean that a usage problem would still throw an exception early, but a `null` would be allowed because the policy would be to allow the API to return the validation problem.

Here's a straw man implementation. Thoughts?

``` patch
diff --git a/lib/StripeMethod.js b/lib/StripeMethod.js
index 7eef1b3..be7e222 100644
--- a/lib/StripeMethod.js
+++ b/lib/StripeMethod.js
@@ -45,7 +45,14 @@ function stripeMethod(spec) {
           urlData[param] = '';
           continue;
         }
-        throw new Error('Stripe: I require argument "' + urlParams[i] + '", but I got: ' + arg);
+
+        // In the case of a missing element at the expected index, throw an
+        // error because this is likely a usage problem that can be caught in
+        // development. A `null` value may still fail, but is allowed to be
+        // ommitted because we'll allow the API to throw the error.
+        if (arg === undefined) {
+            throw new Error('Stripe: I require argument "' + urlParams[i] + '", but I got: ' + arg);
+        }
       }

       urlData[param] = args.shift();
```

**Comment by matthewarkin** [comment]
Yeah, I get and buy the rational for wanting to throw an Error instead of just returning it, despite where it lies in convention.
I think the check for undefined would be a good compromise for me. Though I'd wonder what happen if you did something like 

````js
var data = db.getDetails(id); // data for some reason only contains a customerId propety thus data.subscriptionId is undefined
stripe.subscriptions.get(data.customerId, data.subscriptionId, callback);
````

I think that would still cause the error to be thrown though if something like that was to happen it would likely indicate some larger issue.

My larger thought is that the Stripe docs for JS state that errors would be passed through to the callbacks not that any would be thrown, so the safer bet would be to just return this in a callback since there is a higher likelihood that the user will have some callback to handle the error as opposed to having a try/catch set up.

**Comment by brandur** [comment]
@matthewarkin Fair enough. I hadn't adequately considered that it might be relatively common to be accessing properties in JS that are `undefined` instead of `null`.

I don't have huge interest in keeping the system as is, so I'm just going to change all thrown exceptions to use the return callbacks instead as suggested. See #218. Thanks for the help here!
