### ISSUE TITLE
Add documentation for the the customer methods for manipulating subscriptions

### ISSUE THREAD

**Issue by dininski** [stripe/stripe-node#263]
Currently the customer methods, related to manipulating subscriptions do not have official documentation, at least I wasn't able to find any. In the `README.MD` they are listed, but they are redirecting to manipulating the subscriptions themselves, not the player subscriptions. Currently I am unable to find any docs on methods like `stripe.customers.createSubscription` or `stripe.customers.updateSubscription`. And another question - can one stripe customer pay for another customer's subscription? I guess they should be able by passing the payee's token, but the documentation seems be missing on this.

**Comment by matthewarkin** [comment]
The API has been updated to so that subscriptions are their own top level method.

So what used to be `stripe.customers.createSubscription({})` is now `stripe.subscriptions.create({customer: "cus_9AcAh2xzk4y9mB",...})`

The readme should be updated to reflect that change, but you'll want to use the top level subscription object.

To your second question, in Stripe's eyes the subscription belongs to the customer that is paying for it, however your application logic should be able to come up with a way to link a subscription being paid for by one customer to a user.

**Comment by dininski** [comment]
So if one customer is paying for another user's subscription I should save the user's data/id in the subscription metadata and obtain it afterwards?

**Comment by floatingLomas** [comment]
That would make sense to me.  It would probably make sense to apply the same logic to a customer paying for their own subscription, so that `subscription.metadata['user.id']` [0] was always the 'recipient' of the subscription, no matter who is paying for it.

[0] Metadata are only single-depth key-value stores, so `metadata.user.id` won't work, but since `"user.id"` is a valid string key, `metadata['user.id']` will.  Just FYI.

**Comment by dininski** [comment]
Yeah, but this might add a lot of complexity. For example if I want a parent to be able to pay for their child's subscription for a courses website. How would I be able to track the customer if the father pays for the subscription once and afterwards - the mother. AFAIK you are unable to query the subscriptions based on the 'metadata'...

**Comment by matthewarkin** [comment]
You'd want to keep track of that in your own database since you can query
your own database however you'd like.

**Comment by brandur** [comment]
Hi everyone, thanks a lot for the discussion here!

I'm inclined to weight in with @matthewarkin here: metadata is a useful and minimal construct for tagging Stripe resources with basic metadata, but its limitations will quickly start to show once more complex patterns are built on top of it. For this use case, it does seem like maintaining some information in your own database with references to Stripe's resource IDs would be the most suitable solution.

I'm going to close this issue out for now, but feel free to continue to weigh-in with additional thoughts and or discussion!
