### ISSUE TITLE
Stripe API methods cannot be passed as functions

### ISSUE THREAD

**Issue by ryangreenberg** [stripe/stripe-node#273]
The `stripe` client object provides many functions that correspond to API methods. Most classes, controllers, etc. only need a small subset of these. Rather than giving them the entire client as a dependency, it is convenient to give them a single function. This is particularly nice for testing—you can provide a simple, promising-producing function, rather than a larger object.

Doing this, however, produces an error.

```
var stripe = require('stripe')('my_key');
var obj = { create: stripe.charges.create };
obj.create({});
```

results in

```
TypeError: this.createUrlData is not a function
    at Object.create (.../node_modules/stripe/lib/StripeMethod.js:31:24)
    at repl:1:5
```

The cause of the error is the changed context of `this` as used in StripeMethod, which refers to something other than the StripeResource instance. A workaround is to use a copy of the function which you manually bind to the resource:

```
var stripe = require('stripe')('my_key');
var obj = { create: stripe.charges.create.bind(stripe.charges) };
obj.create({});
```

**Comment by brandur** [comment]
Interesting use case! Thanks for opening.

I took a quick look at this one, and unfortunately it's not super clear to me how you could easily solve this (although I'm only nominally proficient in JavaScript so it's possible there's a trick that I'm missing). Essentially the library was built with certain assumptions, and one of them is that a `StripeMethod` is always going to be grafted onto a `StripeResource`.

I'm going to close this as a wontfix because it's obviously not a supported path, but am definitely open to reviewing a patch if you're able to produce a relatively succinct patch to solve the problem.
