### ISSUE TITLE
Readme contains incorrect documentation for deleteSource method

### ISSUE THREAD

**Issue by jpm** [stripe/stripe-node#297]
The readme documentation specifies the deleteSource as having the following signature:

`deleteSource(customerId, {source: 'source_token'})`

When the method is actually supposed to be the following:

`deleteSource(customerId, source_token)`

This took me a while to diagnose, as these methods are sort of dynamic in the source code, and you can't quite understand what is going on without being an expert at the implementation.

**Comment by fred-stripe** [comment]
Hey, thanks for writing in about this! You're right, the README is a bit out of date with the launch[0] of the sources API[1]. In fact, the `deleteSource` method doesn't quite yet work on the new sources. We're in the middle of updating the API docs around this, and once they're ready we'll likely remove the section listing out API calls and link directly to the node section[2] of our standard API docs as we've done for the other bindings.

Meanwhile, great find here, and thank you for reporting it.

[0]: https://stripe.com/blog/european-payment-methods
[1]: https://stripe.com/docs/sources
[2]: https://stripe.com/docs/api/node

**Comment by brandur** [comment]
Thanks for reporting and sorry about the trouble. As Fred suggestions above, we're working on getting this into our canonical set of reference docs. I'm also suggesting #299 to reduce the likelihood of this type of documentation problem because we currently don't have any good mechanism for keeping the API list in the README up to date.

> This took me a while to diagnose, as these methods are sort of dynamic in the source code, and you can't quite understand what is going on without being an expert at the implementation.

Definitely read you loud and clear on that one. Metaprogramming is sometimes useful, but unfortunately comes with the side effect of making things quite difficult to understand :/ I can't promise a rewrite or anything like it for now, but I'd certainly be interested in trending the code here towards a more explicit form.
