### ISSUE TITLE
High Severity Vulnerability in "qs" - Prototype Override Protection Bypass

### ISSUE THREAD

**Issue by mathieupythian** [stripe/stripe-node#308]
Thanks for this useful package!

Could you update your 'qs' dependency to 6.4.0 in order to avoid a high severity vulnerability.

Many thanks!

References:
https://snyk.io/vuln/npm:qs:20170213
https://www.sourceclear.com/registry/security/prototype-override-protection-bypass/javascript/sid-3638

**Comment by brandur-stripe** [comment]
Hi @mathieupythian,

Thanks for reporting this! I've released a patched version in 4.15.1.

I'm not planning to announce too widely because if I'm reading the vulnerability report right, this seems to be an issue with the parsing side of qs, and we're currently only using it for its `stringify` function which encodes parameters. It's a good idea to update anyway though of course.

**Comment by mathieupythian** [comment]
Thanks for the quick fix!

**Comment by mathieupythian** [comment]
Hi @brandur-stripe,

Do you know when that new version will be available thru npm?  Is that something that you need to push manually?

Thanks,
Jerome

**Comment by brandur-stripe** [comment]
@mathieupythian Sorry. I hadn't notice that my deployment script had failed out near the end.                                                                                                                                        I just pushed it to NPM manually.
