### ISSUE TITLE
Create Subscription Method and Signature in SDK is different from API reference

### ISSUE THREAD

**Issue by MSIH** [stripe/stripe-node#319]
On the Stripe.com, the API reference page has, the method to create a subscription as [stripe.subscriptions.create()](https://stripe.com/docs/api/node#create_subscription) and the signature is:
 ```
stripe.subscriptions.create({
  customer: "cus_AMUZA0sSOgcY4z",
  plan: "Store90"
}
```

While the stripe-node SDK the method to create a subscription is [stripe.customers.createSubscription()](https://github.com/stripe/stripe-node/blob/699d1ba05707bb5000989b1b4117178c174094be/lib/resources/Customers.js) and the [signature ](https://github.com/stripe/stripe-node/blob/699d1ba05707bb5000989b1b4117178c174094be/test/resources/Customers.spec.js)is:

```
stripe.customers.createSubscription('cus_AMUZA0sSOgcY4z', {
          plan: 'Store90' 
        });
```

Please make node SDK match online API reference.

**Comment by remi-stripe** [comment]
@MSIH `stripe.customers.createSubscription()` is the old method. It's been deprecated but it's still available for users that relied on this feature before. The newer method is the one from our documentation and it's been added to our library almost a year [ago](https://github.com/stripe/stripe-node/blob/699d1ba05707bb5000989b1b4117178c174094be/lib/resources/Subscriptions.js#L9).

You'll need to make sure that you're on at least our version 4.6.0 of our library to use this.

**Comment by tezmaster** [comment]
This still seems to be an issue for me the fix you point to show's that 

b49ee6b has: includeBasic: ['create', 'list', 'retrieve', 'update', 'del',],

yet the current version 

bd4bd44 has: includeBasic: ['list', 'retrieve', 'del',],

so when you try to use `stripe.customers.createSubscription()` you get `Cannot read property 'createUrlData' of undefined` ??

**Comment by ob-stripe** [comment]
@tezmaster The current version has `includeBasic: ['list', 'retrieve', 'del',]` because the `create` and `update` methods have custom definitions in order to properly encode the `items` parameter. In the second commit you linked, you can see that the `create` and `update` methods are defined right after the `includeBasic` line.

`stripe.subscriptions.create()` is still the way to go to create subscriptions, as documented in the [API reference](https://stripe.com/docs/api/node#create_subscription).
