### ISSUE TITLE
Coupon creation

### ISSUE THREAD

**Issue by zo-tahiana** [stripe/stripe-node#329]
Hello,

I have a bug when I will create a coupon with `duration: 'repeating'`:
```
stripe.coupons.create({
  amount_off: 1000,
  duration: 'repeating',
  duration_in_months: 6
});
```

It still create a new coupon `10$ off once` instead of `10$ off for 6 months`

Thank you!

**Comment by remi-stripe** [comment]
@zo-tahiana I just tried on my end and after adding `currency` which is also required I get a repeating coupon for 6 months. My code is:

```
stripe.coupons.create({
  amount_off: 1000,
  duration: 'repeating',
  duration_in_months: 6,
  currency: 'usd'
}).then(function(coupon) {
  console.log("Then coupon:\n", JSON.stringify(coupon));
}, function(err) {
  console.log("Error :(\n", JSON.stringify(err));
})
```

The response is:

```
{  
   "id":"3drZS27h",
   "object":"coupon",
   "amount_off":1000,
   "created":1493897993,
   "currency":"usd",
   "duration":"repeating",
   "duration_in_months":6,
   "livemode":false,
   "max_redemptions":null,
   "metadata":{  

   },
   "percent_off":null,
   "redeem_by":null,
   "times_redeemed":0,
   "valid":true
}
```

Can you confirm that you are using this exact code too? The one you shared doesn't have `currency` and would just return an error. Otherwise, can you also confirm whether you're on the latest version of our Node.js library?

**Comment by zo-tahiana** [comment]
I just tried your code and it work well... Thank you!
