### ISSUE TITLE
metadata missing from customer.source object

### ISSUE THREAD

**Issue by rcwwilliams** [stripe/stripe-node#349]
Hi

I realise this may not be considered part of the stripe node package, but I reported this 3 months ago via the stripe support email and have not yet had any technical feedback on the issue.

I have really appreciated how responsive you have been through this channel and so I thought I would chance posting the issue here.  I apologise if I am breaking protocol here.

The issue is that webhooks that contain customer.source objects return empty metadata for the customer.source although API requests return with the metadata correctly populated.

Thanks very much.

Robin

**Comment by remi-stripe** [comment]
@rcwwilliams This is something that we are aware of but not something we plan to fix immediately. For now, you would need to retrieve the source via the API to get the corresponding metadata directly.

I'm going to close the issue here as you mentioned this is just for bug reports in the library and unrelated to this problem.

I'll make sure to raise the issue again internally so that we can plan a fix in the future.

**Comment by rcwwilliams** [comment]
Thanks Remi

We use metadata to determine which of our systems will handle the webhook and that works very effectively for all other webhook types.  But for charges and card updates, all of our systems need to process the webhook including making an extra API call before they can determine whether or not the webhook is for them.

So a fix for this would be really appreciated.

Thanks

Robin
