### ISSUE TITLE
Received unknown parameter: type

### ISSUE THREAD

**Issue by JoysonAnto** [stripe/stripe-node#354]
I am integrating bitcoin with stripe when iam giving type of stripe to bitcoin or the response type in my php code it throws 'Received unknown parameter: type' Kindly help me with integrating bitcoin. Thanks in advance
/*******form integration*****/

	<form action="site/checkout/UserPaymentCreditStripe" method="POST">
          <script
                 src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<?php echo $stripe_code['publishable_key']; ?>"
                  data-amount="50"
                    data-name="project name"
                     data-description="2 widgets ($20.00)"
                  data-image="/img/documentation/checkout/marketplace.png"
                 data-label="Pay with Card or Bitcoin"
                 data-locale="auto"
                   data-currency="usd"
              data-bitcoin="true">
        </script>
      </form>

     /******php integration*******/

    $token = $this->input->post('stripeToken');
    $stripeTokenType= $this->input->post('stripeTokenType');
     try {
				$payment_result = 	Stripe_Charge::create(array(
					 "type" => $stripeTokenType,#"bitcoin",
					"amount" => $amounts, # amount in cents, again
					"currency" => "USD",
					
					"source" => $token,
					"description" =>'officebnbtest'
					#"description" =>$enquiryid
						)
				);
     } catch (Exception $e) {
				$error = $e->getMessage();
				echo "<pre>"; print_r($error); echo "</pre>";
				
				$this->session->set_userdata(array('payment_error' => $error));
				//redirect('order/failure'); 
			}

**Comment by remi-stripe** [comment]
@JoysonAnto This repository is here to discuss issues with the Stripe-node library for Node.js developers. This is unrelated to your code which uses Checkout and PHP. The issue here is that you're mixing a Charge creation with a really old version of our SDK (before February 2015) and Source creation.

None of this would work unfortunately and you'll need to upgrade your PHP library for Stripe to the latest (4.12.0) and read our documentation in details about source creation: https://stripe.com/docs/sources/bitcoin

If you have any follow up questions, please make sure to talk to our support team directly: https://support.stripe.com/email
