### ISSUE TITLE
Cannot find module 'stripe'

### ISSUE THREAD

**Issue by ekoome** [stripe/stripe-node#410]
I'm getting the above error when trying to import stripe 5.3.0 using Node 6.9.1, tsc 2.1.4. Using instructions under https://github.com/stripe/stripe-node

I have installed stripe npm install `stripe --save && npm install @types/stripe --save-dev`

`const stripe = require('stripe')('sk_.......'); `//Error here! "Cannot find module stripe"

Tried adding paths in tsconfig "stripe": ["node_modules/stripe/lib/stripe.js"]  but this has not helped.

Anything i'm missing?

**Comment by remi-stripe** [comment]
@ekoome Did you install the library in your system first? You can read more about this here.

**Comment by ekoome** [comment]
Yes - Using instructions under https://github.com/stripe/stripe-node

I have installed stripe npm install stripe --save && npm install @types/stripe --save-dev

**Comment by remi-stripe** [comment]
Are you trying to run this code server-side or client-side? The stripe-node library is a server-side component and can not be used in the browser.

**Comment by ekoome** [comment]
This code is running server-side in node.

**Comment by fred-stripe** [comment]
If `require()` fails to load a module it's most likely a problem with your local setup and not anything specific to the Stripe module. It looks like you've been in touch with Stripe Support, so the best course for resolving this problem is to work with them and provide more specific details about your package configuration, etc. I tested the steps you listed on Node v6.9.1 as well and was able to load the module and make API requests as expected.

What I'd recommend as a next diagnostic step (and support will likely say the same) is to create a fresh project elsewhere on your machine, install the `stripe` module and run an example program to make sure your Node environment is functioning properly. I'm going to close this issue for now, but we can revisit and reopen if necessary.
