### ISSUE TITLE
StripeInvalidRequestError 

### ISSUE THREAD

**Issue by vishvas-prajapati** [stripe/stripe-node#423]
`
let obj = {
  amount: 2500,
  currency: 'usd',
  customer: 'cus_CJIGVr6qKh8Lm6',
  source: {
    object: 'card',
    currency: 'usd',
    exp_month: 12,
    exp_year: 2019,
    number: 5555555555554444,
    name: 'Demo Card'
  }
};
stripe.charges.create(obj);
`

while using above code, I got stripe error as mention below
{ Error: Invalid string: {"object"=>"card", "currency"=>"usd", "exp_month"=>"12", "exp_year"=>"2019", "number"=>"555555******4444", "name"=>"Demo Card"}

**Comment by remi-stripe** [comment]
@vishvas-prajapati When you create a charge and pass a customer id (cus_1234) in the `customer` parameter, you can not also pass card details in the `source parameter. This would not work as we expect a card id (card_AbcD) instead of a card already saved on the customer.

If you have a new card, you have to save it on the customer first using the Create Card [API](https://stripe.com/docs/api#create_card). You can then call the Create Charge [API](https://stripe.com/docs/api#create_charge) and pass the new card id in `source`.

Separately, you really should not be passing card details server-side. This impacts your [PCI compliance](https://stripe.com/docs/security#validating-pci-compliance) which is unlikely to be what you want. You should tokenize client-side using [Stripe Checkout](https://stripe.com/docs/checkout) or [Elements](https://stripe.com/docs/stripe-js#elements).

Since this is not a bug in the library, it would be better to talk about this directly with our support team if you have any follow up questions. You can contact them here: https://support.stripe.com/email
