### ISSUE TITLE
Crash when creating product

### ISSUE THREAD

**Issue by thousight** [stripe/stripe-node#448]
I am trying to create a product in stripe, but when I try to make the call with stripe.products.create(), it lags, and some seconds later my server crashes due to 'JavaScript heap out of memory'.

Here is how I do it:
```
import stripePackage from 'stripe'
const stripe = stripePackage(config.stripe)

// after product is found in mongoose
stripe.products.create({
    id: product.sku,
    name: product.title,
    type: 'good',
    description: product.description,
    active: product.isAvailable,
    images: product.images,
    package_dimensions: {
        weight: product.shipping.weight * 16,
        length: product.shipping.dimension.length,
        width: product.shipping.dimension.width,
        height: product.shipping.dimension.height
    },
    shippable: true
}).then(stripeProduct => {
    console.log(stripeProduct.id);
    res.json(stripeProduct)
}).catch(err => {
    if (err) {
        console.log(err);
    }
})
```

Here is the crash report from express.js:
```
<--- Last few GCs --->

[87147:0x102801e00]    61928 ms: Mark-sweep 1416.8 (1462.3) -> 1416.7 (1446.3) MB, 9502.3 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 9502 ms) last resort
[87147:0x102801e00]    72192 ms: Mark-sweep 1416.7 (1446.3) -> 1416.7 (1446.3) MB, 10263.3 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3ca24589cef1 <JSObject>
    1: encode(aka encode) [/Users/thousight/Projects/Project/node_modules/qs/lib/utils.js:~118] [pc=0x163bec732a95](this=0x3ca245882241 <undefined>,str=0x3ca2458822c1 <true>)
    2: arguments adaptor frame: 2->1
    3: stringify(aka stringify) [/Users/thousight/Projects/Project/node_modules/qs/lib/stringify.js:~32] [pc=0x163bec733b44](this=0x3ca245882241 <undefined>,object=0x3ca24588...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::LoadIC::LoadFullChain(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Smi>) [/usr/local/bin/node]
 6: v8::internal::LoadIC::UpdateCaches(v8::internal::LookupIterator*) [/usr/local/bin/node]
 7: v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>) [/usr/local/bin/node]
 8: v8::internal::Runtime_LoadIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 9: 0x163bec5840dd
10: 0x163bec732a95
```

Is there anything wrong with it? What would be the factors to cause that server crash? Thanks

Node: v8.4.0
Stripe-Node: v5.8.0

**Comment by brandur-stripe** [comment]
Hey @thousight,

In an error message like "JavaScript heap out of memory", the "heap" they're referring to is [a segment of memory earmarked for the JavaScript VM to use for object allocation](https://en.wikipedia.org/wiki/Memory_management#HEAP). When you see an error like this, it means that that heap is at its largest allowed extent, and the runtime failed because it didn't have the space required to allocate a new object.

_Probably_ what you're going to want to do to solve this is tell Node's underlying V8 option that you want a bigger heap. For example, this will allow 4 GB of memory for the VM's "old space", which is the generational GC's bucket for long-lived objects:

```
node --max-old-space-size 4096 <normal options>
```

(You can see documentation for these hidden V8 options with `node --v8-options`.)

If you're already doing this, then it might also be that you have a memory leak somewhere. Given though that in this case the allocation that pushed you over didn't even originate in `stripe-node` (it actually came from the `qs` package used to form-encode parameters), so far the evidence doesn't seem to suggest that this is a problem in this package.

I hope that helps a bit. I'm going to close this out for now.
