### ISSUE TITLE
Is it possible to `expand` anything (like `balance_transaction`) during `stripe.charges.create`?

### ISSUE THREAD

**Issue by tinovyatkin** [stripe/stripe-node#454]
Hello,

As per https://stripe.com/docs/api/node#expanding_objects regarding `expand` parameter _This parameter is available on all API requests, and applies to the response of that request only_.

However, as per library source code you are whitelisting optional parameters in _basic methods_ (such as `charges.create`)  to `OPTIONS_KEYS = ['api_key', 'idempotency_key', 'stripe_account', 'stripe_version']`.

So, is it possible to expand any field during creating a charge?

**Comment by remi-stripe** [comment]
@tinovyatkin The whitelist is because those extra parameters should be in the second hash and not the first one. Expanding works fine on any API requests and if you try you should be able to confirm this quickly.

Here's a basic runkit example confirming it works: https://runkit.com/5a6b26c0e3908200129fbb5d/5ae9af7f843fb6001223efd6
