### ISSUE TITLE
Support for Stripe's stripe-mock

### ISSUE THREAD

**Issue by techieshark** [stripe/stripe-node#472]
This is either a feature request or a question.

I'd like to try https://github.com/stripe/stripe-mock but my server code is running stripe/stripe-node and it's not clear how one should tell the library to use a different host (`localhost`) and port (`12111`).

Would it be possible to add an good way to set those?

**Comment by ob-stripe** [comment]
Hi @techieshark! You can use [`Stripe.setHost()`](https://github.com/stripe/stripe-node/blob/edea14167f77b85b741b90b012e0d2e5061f11d2/lib/stripe.js#L116-L124) and [`Stripe.setPort()`](https://github.com/stripe/stripe-node/blob/edea14167f77b85b741b90b012e0d2e5061f11d2/lib/stripe.js#L130-L132) to change the default hostname and port, or simply `Stripe.setHost()` and pass the port as the second argument:

```js
Stripe.setHost("localhost", 12111);
```

Closing the issue since this is already possible, but feel free to reply!

**Comment by techieshark** [comment]
Thanks @ob-stripe, that worked well.
