### ISSUE TITLE
stripe error with StripeConnectionError

### ISSUE THREAD

**Issue by danglq** [stripe/stripe-node#479]
i used stripe with nodesj 8.11.3 but met error StripeConnectionError
at Object.onceWrapper (events.js:313:30)
0|www      |     at emitNone (events.js:106:13)
0|www      |     at ClientRequest.emit (events.js:208:7)
0|www      |     at TLSSocket.emitTimeout (_http_client.js:706:34)
0|www      |     at Object.onceWrapper (events.js:313:30)
0|www      |     at emitNone (events.js:106:13)
0|www      |     at TLSSocket.emit (events.js:208:7)
0|www      |     at TLSSocket.Socket._onTimeout (net.js:410:8)
0|www      |     at ontimeout (timers.js:498:11)
0|www      |     at tryOnTimeout (timers.js:323:5)
0|www      |     at Timer.listOnTimeout (timers.js:290:5)
0|www      |   type: 'StripeConnectionError',

with the same on server but i use laravel with stripe then ok. use the same api and key
 stripe.tokens.create({
            card: {
                "number": '4242424242424242',
                "exp_month": 12,
                "exp_year": 2019,
                "cvc": '123'
            }
        }

**Comment by remi-stripe** [comment]
This looks like an outdated openssl version installed, at least the one used by your Node.js environment. You should look into upgrading your openssl version on your system to a more recent ones.

You also should not be creating tokens with stripe-node as this library is used server-side. Card details should be collected client-side via Elements: https://stripe.com/docs/stripe-js#elements

**Comment by onidnalbj** [comment]
Hey @danglq 

This error is due to the obsolete version that you have of OpenSSL (the one of the system) since it is having connection problems through the TLSSocket.

Update the version and try again, use the same version as you (not in the same scenario) but I did not have that error since I have the OpenSSL updated.

**Comment by danglq** [comment]
@onidnalbj Thank you so much

**Comment by AviIhej** [comment]
I am getting the same error when I try to create a customer and charge that customer: 
` Error: An error occurred with our connection to Stripe`. Has anybody figured it out yet? I am running my application on localhost:3000 and I am using a graphqlQL mutation to make the API call.

**Comment by ob-stripe** [comment]
@AviIhej `StripeConnectionError`s can be caused by a number of different things. I recommend you reach out to Stripe's support at https://support.stripe.com/email and include any relevant information in your message, such as:
- your Node.js and stripe-node versions
- timestamps of the failed requests
- full stack trace of the error
