### ISSUE TITLE
question which is similar to #265

### ISSUE THREAD

**Issue by Koshukey** [stripe/stripe-node#484]
In #265, it is talked about "Module not found: Error: Cannot resolve module 'child_process'".

I face the same issue and cannot figure out.

I am using react-stripe-checkout with next.js, react.js and firebase.

It means that I do not have a backend server.

I understood

```

the stripe Node module is only meant to be used server-side


```
However, I am confused what I should do to use stripe-node to run stripe payment API.

Can u give some advise?

**Comment by remi-stripe** [comment]
@Koshukey A server is required to use Stripe today. Client-side you create a card token or a source with Checkout or Elements. Once you have that token or source id, you send it to your server where your code would run.

Since you use Firebase, you don't have to use stripe-node yourself directly. You would use Firebase's functions to handle the charge creation. You can see a tutorial here: https://firebase.google.com/docs/use-cases/payments

I'm closing this issue as it is not really a bug with the library itself but you can follow up with Firebase's support team if you have issues using their tutorial.
