### ISSUE TITLE
Apple Pay test token

### ISSUE THREAD

**Issue by peterjuras** [stripe/stripe-node#497]
Hi!

Is there an apple pay specific test token which can be used to test apple pay flows? I'd be looking for a token that is similar to other test tokens from the [Testing guide page](https://stripe.com/docs/testing#cards).

Kind regards,
Peter

**Comment by remi-stripe** [comment]
@peterjuras Unfortunately this is not something we support today. You would have to go through the flow in Test mode to get one, that's the only way.

I'm closing this out since it's not a question or bug about our stripe-node library. If you have any follow up questions do not hesitate to ask our support team: https://support.stripe.com/email
