### ISSUE TITLE
Differences between creating invoice manually vs with API

### ISSUE THREAD

**Issue by andreverbenergy** [stripe/stripe-node#518]
When creating an invoice on the dashboard, you create the line items specific to the invoice.

When creating an invoice with the API, unless I'm missing something in the docs, there's no way to pass line items manually, you have to create them with separate API calls, and then make the call to create the invoice, which then pulls all open line items associated with the customer. 

I can't seem to find a way to only assign specific line items to a specific invoice without it pulling all of them.

Is there a reason for this difference/am I missing something?

**Comment by remi-stripe** [comment]
@andreverbenergy The reason is mostly for backwards compatibility reasons. For a long time, it was not possible to create an empty invoice and you always need to have invoice items on the customer. If we were to change this behavior, it would be a breaking API change.

For now, we limited the feature to the dashboard where it's easy to do custom work. We're hopeful that we can add this feature in the future but for now you have to create at least one invoice item before creating the invoice.

Since github issues are specific to bugs with the library itself, I will close this out, but I shared your feedback with our engineering team. You can do the same via our contact form [here|https://support.stripe.com/email]

**Comment by andreverbenergy** [comment]
If an invoice is unable to be created, is there a standard way to delete the invoice items associated with it so that the next invoice created doesn’t automatically include them?

**Comment by remi-stripe** [comment]
You can delete pending invoice items via the API: https://stripe.com/docs/api#delete_invoiceitem
