### ISSUE TITLE
Transaction Support

### ISSUE THREAD

**Issue by fishcharlie** [stripe/stripe-node#540]
It would be awesome to have support in this package to be able to make multiple requests at once with transaction support.

There are many cases where you have to make multiple Stripe calls which all represent 1 business action or something like that. If one of these requests fails all of them should fail, and no action should be taken, if all of them succeed all of them should succeed.

A great example of this is when upgrading a subscription. According to the [Stripe documentation](https://stripe.com/docs/billing/subscriptions/upgrading-downgrading):

> If you want the customer to immediately pay the price difference when switching to a more expensive plan on the same billing cycle, you need to [generate an invoice](
https://stripe.com/docs/billing/invoices/subscription#generating-invoices) after making the switch.

It would be great if you could change the subscription, generate the invoice, attempt to pay the invoice, all in 1 action, and if any one of those items fails, they all fail and no action is taken.

Currently, if [paying the invoice](https://stripe.com/docs/api/invoices/pay) fails, I have to change the subscription back to the original product, and also void the invoice. Which of course, increases the risk of even more failures or bugs.

So if any one of those 3 actions fails, none of them succeed and it's like the request was never made.

This change would probably require changes to how Stripe works on the backend to ensure stability.

**Comment by remi-stripe** [comment]
@fishcharlie This is definitely something we would like to support in the future but it is not on our roadmap for now unfortunately. This is not really a library feature per-se and more something we'd need to build in the API first.

Separately, for the specific example you mentioned, we also plan to support synchronous upgrade/downgrade where a charge would be attempted and the upgrade/downgrade would only work if the associated charge succeeded. Similarly, we don't have a timeline for this but hope to ship it in the future.

I'll close the issue here since it's not really a feature in stripe-node but don't worry it's something we're already aware of and thinking about!

**Comment by fishcharlie** [comment]
@remi-stripe Is this something I should submit a support request for as well? Or because you are aware of it, is that unnecessary? Hopefully it'll get put on your roadmap soon because it would be super useful! Thanks for your help.

**Comment by remi-stripe** [comment]
@fishcharlie This is something we're already aware of so I don't think there's a need for a support ticket. To be candid I don't think this will be on the roadmap anytime soon, at least it's not something we're actively investigating today but it's definitely on our radar!
