### ISSUE TITLE
Allow updating of customer:invoicing:email_to

### ISSUE THREAD

**Issue by adamreisnz** [stripe/stripe-node#571]
I am unable to update these properties of a customer through the API:

![image](https://user-images.githubusercontent.com/490562/53389068-a8e59d80-39f2-11e9-9b65-8af60d459830.png)

The error returned is `Received unknown parameter: invoicing`
Does this error originate from the Node SDK (parameter checking) or from the API itself?

Can we add support to update these fields? I really need to be able to update a customer's billing email address, which is often different from their main email address.

**Comment by remi-stripe** [comment]
@adamreisnz Github issues should be limited to bugs with the library itself. What you're asking for is not supported in the API yet which is why you can't set them. I'd recommend raising this feedback to our support team directly [here](https://support.stripe.com/contact?email=true). It's something we're hoping to ship long term but for now this is Dashboard only.

**Comment by adamreisnz** [comment]
Ok thank you, I wasn't sure if it was a library limitation or API limitation.
