### ISSUE TITLE
library does not implement connect account token

### ISSUE THREAD

**Issue by chrishiestand** [stripe/stripe-node#576]
Trying to implement the api documentation example shown here:

https://stripe.com/docs/api/tokens/create_account?lang=node#create_account_token-account

```javascript
  const stripe = Stripe("sk_test_1234abc");

  const token = await stripe.tokens.create({
    account: {
      legal_entity: {
        first_name: "Jane",
        last_name: "Doe",
      },
      tos_shown_and_accepted: true,
    },
  });
```

Fails with:

>     Received unknown parameter: account[legal_entity]
> 
>       at Constructor._Error (node_modules/stripe/lib/Error.js:12:17)
>       at Constructor (node_modules/stripe/lib/utils.js:138:13)
>       at new Constructor (node_modules/stripe/lib/utils.js:138:13)
>       at Function.Object.<anonymous>.StripeError.generate (node_modules/stripe/lib/Error.js:57:12)
>       at IncomingMessage.<anonymous> (node_modules/stripe/lib/StripeResource.js:163:39)

Looking at the source code, I can see token implementations for card, pii, and bank account. But not for connect account tokens.

stripe npm version: 6.25.1

**Comment by remi-stripe** [comment]
@chrishiestand The issue is not with the library itself here. As you can see the code runs and the request reaches Stripe. You're getting an error here because you are sending `legal_entity` which was deprecated on the latest API version [2019-02-19](https://stripe.com/docs/upgrades#2019-02-19). Instead, you would have to pass `company`, `business_profile` and such.

Don't hesitate to contact our support team if you have any follow up questions though: https://support.stripe.com/contact

**Comment by chrishiestand** [comment]
Sorry for the false alarm and thanks for the fast reply @remi-stripe! I had assumed the documentation would automatically be updated for my latest api, but I suppose that doesn't happen, or at least not everywhere.
