### ISSUE TITLE
Docs: Email in token object

### ISSUE THREAD

**Issue by sseppola** [stripe/stripe-node#586]
Hi,

I'm setting up Checkout to handle payment for a site I'm building. When creating the charge from the backend I want to send a receipt to the user, however the TS definition of the token object does not include the `token.email` property even though it exists in the returned token object.

The TS definitions themselves are trivial to update, the problem is that your docs also do not specify the email property (https://stripe.com/docs/api/tokens/object), and so I'm not sure what is the expected behavior here.

Is there always a `token.email` or just sometimes? And if it's not supported, where do I get the email the user enters in Checkout?

**Comment by remi-stripe** [comment]
@sseppola When you use Checkout, we automatically submit the token id `tok_123` in `stripeToken` and the email address in `stripeEmail`. This means that you don't have to try and fetch it from the `Token` object, and it's already accessible directly

If you use Custom Checkout, we recommend that you explicitly submit the email and and the token id to your back-end instead of submitting the entire `Token` object as JSON. This is more efficient and avoids an unnecessary extra call to Token Retrieve.

We don't document the `email` property on `Token` because it's mostly used internally and not something we recommend that you rely on.
