### ISSUE TITLE
Error: Received unknown parameter: requested_capabilities for stripe.accounts.create

### ISSUE THREAD

**Issue by UniWrighte** [stripe/stripe-node#596]
I'm receiving this error:

`error: Error: Received unknown parameter: requested_capabilities`

when, directly from the documentation, running this code:

`stripe.accounts.create({
  	type: 'custom',
  	country: 'US',
  	email: 'bob@example.com',
  	requested_capabilities: ['card_payments']
	});`

On the newest version of the library. I'm returning it and handling it as a promise on node 11. 

It appears `requested_capabilities` along with almost any other field that isn't type, country, or email gives me and `unknown parameter` error

**Comment by remi-stripe** [comment]
@UniWrighte `requested_capabilities` is a parameter that was added in API version [2019-02-19](https://stripe.com/docs/upgrades#2019-02-19). You get that error because your account is on an older API version and you haven't forced it in the library. You should pin to a version as documented [here](https://stripe.com/docs/api#versioning)

**Comment by UniWrighte** [comment]
Thank you for the quick response. It slipped past me because I'm using my old account to test for a recently opened account of one of my clients. 

Best wishes

**Comment by lonniep123** [comment]
Thanks remi that fixed it for me.
