### ISSUE TITLE
Issue when creating plans on connected accounts

### ISSUE THREAD

**Issue by mcousillas6** [stripe/stripe-node#633]
Node version: `10.5.3`.
Stripe-node version: `6.28.0`.

I'm having issues with the following api call:
```javascript
const plan = await stripe.plans.create(
      {
        amount: 1000,
        interval: 'month',
        product: {
          name: 'some name;',
        },
        currency: 'usd',
      },
      { stripe_account }, // this is the account_id of the user's connected account
    );
```
If I understood correctly, this should create a product and plan on the user's connected account, since i'm using the header authentication.

The issue is that The product and plan are getting created on my stripe account every time.
Am I missing something?

**Comment by ob-stripe** [comment]
Hi @mcousillas6. This code looks correct to me and should do what you expect.

The most likely explanation is that the `stripe_account` variable contains the ID of your platform's account instead of the connected account.

You should reach out to Stripe's support at https://support.stripe.com/email and include information about the request, such as the exact time the request was sent or the request ID. Our support staff will be able to check your account's logs and help you figure out what's happening exactly.

Closing since this doesn't appear to be an issue with the stripe-node library, but feel free to reply if you have reason to believe otherwise.
