### ISSUE TITLE
use_stripe_sdk.   when creating a paymenintent

### ISSUE THREAD

**Issue by giorgio80** [stripe/stripe-node#637]
hello.  
having a connect platform with node js backend and iOS in front. 

actually I'm asking customer account and cards object in my db.   I'm migrating to new payment intents.    So the iOS app call the function that create the payment intents as destination charge and putting on the fee  and passing the confirm = true as parameter.  

```node
return await stripe.paymentIntents.create({
  payment_method_types: ['card'],
  amount: 1000,
  currency: 'eur',
  application_fee_amount: 10,
  customer: customer,
  payment_method: card,
  confirmation_method: 'automatic',
  confirm:true,
  transfer_data: {
    destination: 'acct_11111111111111111111',
  }
})
```

I then pass back the payment intent to the app who gonna open the page to confirm the payment.  

PROBLEM

the payment intent always report next action as "use_stripe_sdk: 

```
 "use_stripe_sdk" =         {
            "stripe_js" = "https://hooks.stripe.com/3d_secure_2_eap/begin_test/src_1Ega3MJBBAFk3hwIOEIala6t/src_client_secret_FAvvQ1UDEOtEDucophApwOG6";
            type = "three_d_secure_redirect";
```

this way,   when creating the redirect context I' always getting NIL.  
it then a way to force with url instead of "use stripe SDK" so I can finish the authentication on the app?

**Comment by giorgio80** [comment]
also,  is this case going into here?: 

https://stripe.com/en-it/guides/strong-customer-authentication#merchant-initiated-transactions-including-variable-subscriptions

**Comment by ob-stripe** [comment]
Hi @giorgio80. You're probably using the `4000 0000 0000 3220` test card number described here: https://stripe.com/docs/testing#three-ds-cards. This test number forces the use 3DSv2.

In any case, this behavior is caused by the API, not the stripe-node library. GitHub issues are not a support channel for Stripe's API so we cannot help you here. Please reach out to Stripe's support at https://support.stripe.com/email instead.

**Comment by giorgio80** [comment]
ok, gonna go to support for that. 
btw , why are you asking me about 3dsv2? I'm effectively using this card as I need to implement 3dsv2 strong authentication. it is unsupported by node? 

thanks

**Comment by ob-stripe** [comment]
It is supported, I simply meant that the issue you described sounds like the expected behavior to me. I'm not very familiar with the Payment Intents API though, support will be able to clarify if that's the case or not.

**Comment by ir-fuel** [comment]
@giorgio80 did you manage to solve this?

**Comment by aliriaz-stripe** [comment]
Hi @ir-fuel ,  @giorgio80 

Since you're planning on confirming the PaymentIntent client-side and passing `confirm: true` on PaymentIntent creation, you would also need to specify the `return_url` [0] to the PaymentIntent at creation/confirmation time. 

Since you are confirming on the client-side, you should not pass `confirm: true` on the server-side, and then confirm on the client-side (your iOS app) and pass the `returnURL` on STPPaymentIntentParams instead.

[0] https://stripe.com/docs/api/payment_intents/confirm#confirm_payment_intent-return_url

**Comment by Gior80** [comment]
Hello Oliver , yes solved that , think we can close :) 

Thanks !
