### ISSUE TITLE
Definitely Typed does not have definitions for Checkout API

### ISSUE THREAD

**Issue by rclayton-the-terrible** [stripe/stripe-node#643]
The current TypeScript definitions for the 7.1.0 client do not include the checkout API described here: https://stripe.com/docs/payments/checkout/server

**Comment by ob-stripe** [comment]
Hi @rclayton-the-terrible. The TypeScript definitions for Stripe's Node.js library on the Definitely Typed repository are not maintained by Stripe, so you would have to make a request directly over there. It looks like they already have an open issue for this: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34968.

Since this is out of Stripe's control, I'm closing the issue. In the future, we will be shipping official TypeScript definitions for the library (cf. #296).
