### ISSUE TITLE
You can't delete invoices created by subscriptions.

### ISSUE THREAD

**Issue by chemitaxis** [stripe/stripe-node#657]
Hi, we are retrieving an invoice from an user that has been update to a new subscription.

We retrive the invoice: 

`const invoice = await stripe.invoices.retrieve('in_1EudqzBn82mIxvX2CQAf****');`

And the status of the invoice is draft (`status: 'draft'`), but when I try to delete the invoice like this:

`await stripe.invoices.del('in_1EudqzBn82mIxvX2CQAfLwPZ');`

I have this error:

> You can't delete invoices created by subscriptions.

Why I can't delete this invoice?

This is all the flow:

```
    // update the subscription of the user to a new plan
    await stripe.subscriptions.update('sub_XXXXXX', {
      plan: 'NEW_PLAN_ID',
      prorate: true
    });

    // We need to do the INVOICE to the user:
    invoice = await stripe.invoices.create({
      customer: 'cus_XXXX',
      subscription: 'sub_XXXXXX'
    });
    
    // The user pay the invoice, but sometimes, the customer 
    // don't have enough funds in the credit card, and I want to rollback the operation
    const payment = await stripe.invoices.pay(invoice.id);
```

Thanks!!

**Comment by remi-stripe** [comment]
@chemitaxis You can not delete invoices associated with Subscriptions. Since you do not create those, Stripe does on each new billing cycle, those are needed to track the history of the subscription. You can only delete invoices that you created yourself as drafts for example in the Dashboard.

I'm going to close as this is not a bug in the library. If you have any follow up questions though do not hesitate to reach out to our support team: https://support.stripe.com/contact

**Comment by adamreisnz** [comment]
This is horrible. We shifted a customer from monthly to annual billing via the UI, and this incorrectly created a new subscription from today as opposed to the 1st of next month.

I then went to cancel this subscription, since there was no way to edit it, and the draft invoice still remained in place, with no way for us to delete it. Really poor experience, and I fail to see why we shouldn't be allowed to delete automatically created invoices.

Now the customer will receive an invoice for a subscription that has already been cancelled, and I have to explain to them why this happened, and why they will receive another subscription for the actual new subscription that I have to create now... 😩

**Comment by remi-stripe** [comment]
@adamreisnz Sorry for the frustration here. I'd recommend reaching out to our support team for something like this: https://support.stripe.com/contact

**Comment by kkukshtel** [comment]
I'm running into a few more issue here around this. Not only can you not delete auto created invoices, but I'm also unable to delete subscription line items (due to what I assume is the same sort of thing). I'm relying on the invoice.created event, and am trying to handle that invoice by (since I can't delete it or void it), trying to just remove the line item, but am blocked here as well.

Though I can see the line item id on the invoice via the API, and I can also use the line item api to get the details of that item specifically, when I try to delete it I get the error that there is "No such invoiceitem". Though it's clearly there.

I have no idea what to do with this invoice and it seems the only thing I can do successfully is to add other items onto it. Would love any sort of guidance on how best to handle these invoices to just get them to 0.

**Comment by remi-stripe** [comment]
@kkukshtel You can not edit a line item associated with a subscription item. Those are immutable on an invoice once the invoice has been created. You can add _new line items_ to offset something, for example to add an extra fee or discount. If you need to get that invoice's amount to 0 you would add a line item for a negative amount equal to the amount due on that invoice.

This is less about the stripe-node library and more about the API itself tough and talking to our support team would be better. You can explain your business model, provide example invoices to look at and they can work with the product teams on addressing your feedback!

**Comment by kkukshtel** [comment]
@remi-stripe Thanks for getting back! Good to know that you can't edit a sub line item in any way. That's definitely something (along with the inability to delete subscription invoices) that I think would be great to have reflected in the documentation.

I actually have been on two calls with Stripe support in the past two days about how to best handle this state. The first person suggested doing what you said, which is adding another item to the invoice to offset the charge. The other person I talked to in support actually _didn't know_ that you couldn't delete subscription invoices, and made a note of it and said he would talk to the rest of the team.

Because I'm also intending to cancel someone's subscription in this moment, the flow I ultimately landed on, which was suggested by the second person I talked to, was to void the invoice. However because you can't directly void a draft invoice, this ended up being my function chain to void an invoice and cancel a subscription:

1. Delete the subscription (also turns auto progression off automatically)
2. Update the invoice with a note to say the sub was voided for X reason
3. Finalize the invoice
4. Void the invoice

This successfully "kills" an invoice generated by a subscription and doesn't leave something hanging out in draft mode.

**Comment by remi-stripe** [comment]
@kkukshtel That does seem like the right flow in this specific case!

**Comment by rvvincelli** [comment]
We are experiencing the same issue, and this [workaround](https://github.com/stripe/stripe-node/issues/657#issuecomment-544992250) sounds good, but the thing is: the customer is deleted, so Stripe won't let us touch the invoice at all. Any hints are welcome!

**Comment by Tiedye** [comment]
If you just want to delete one invoice without deleting sub do: set `auto_advance: false` on invoice -> finalize invoice -> void invoice
