### ISSUE TITLE
Can't install stripe on node 10 LTS

### ISSUE THREAD

**Issue by clementdevos** [stripe/stripe-node#689]
Hi, 

I've been trying to update stripe-node to the latest 7.8.0 version but using yarn or npm, i can't npm install the library due to deprecations in node

This is the logs i get : 

`npm install stripe`

```

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.16.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.16.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../../nan/nan.h:839:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/clementdevos/.node-gyp/10.16.3/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
...
```

Any idea what's happening here? 

Cheers,

Clément

**Comment by ob-stripe** [comment]
Hi @clementdevos. I don't think this problem is related to stripe-node. stripe-node has only one dependency (qs) which itself has no dependencies.

I've googled the error and I think it might be an issue with npm itself: https://github.com/npm/npm/issues/17333. You can apparently fix the issue by forcing an install of the latest version of fsevents: https://github.com/fsevents/fsevents/issues/181#issuecomment-425242530.

Closing, but feel free to reply.

**Comment by clementdevos** [comment]
Hi, thanks for the quick reply, i'll look further into it !
