### ISSUE TITLE
Feature request: Open connect and checkout in new tab

### ISSUE THREAD

**Issue by smithb1994** [stripe/stripe-node#700]
Currently checkout and connect redirect the user to stripe. It would be nice to open stripe in a new tab rather than redirecting them away. 
If this feature already exists, please let me know.

**Comment by remi-stripe** [comment]
@smithb1994 For Connect you can always open this in a new tab yourself since you control the URL and the button. For Checkout though this is not possible today but we've heard that feedback before so I'll flag it again internally.

Github issues are limited to bugs with the library itself and since your feedback is about the API and products I would recommend also raising it directly to our support team here: https://support.stripe.com/contact

**Comment by smithb1994** [comment]
I guess an interim solution would be to open a new tab and *then* run stripe's redirect function from there.
Regardless, thanks for the consideration.

**Comment by wwwmaster1** [comment]
Thanks for the alternate solution, but I too would have liked the option to target  a _blank window.

**Comment by pirate** [comment]
We need this as well because we're a music site, so if we redirect users in the current tab the music will stop playing, which is a pretty steep detriment to user experience. Would be great to have a `target` option on `redirectToCheckout` so we could force it to open in a new tab.

**Comment by remi-stripe** [comment]
@pirate Until we build an alternative, you could open a new tab first that will then handle the redirect for example in that case. I hope this fixes the immediate issue!
