### ISSUE TITLE
Stripe is not defined

### ISSUE THREAD

**Issue by 24dev** [stripe/stripe-node#713]
When attempting to open the default Stripe checkout, I am running into this error: ```502: Stripe is not defined```

My code is here, and I'm using Netlify (AWS Lambda) functions:

index.html: 
```
<script src="https://js.stripe.com/v3/"></script>
```

checkout.js:
```
exports.handler = async function(event) {
  const stripe = Stripe(STRIPE_SECRET_KEY);

  const {error} = await stripe.redirectToCheckout({
    items: [{
      // Define the product and plan in the Dashboard first, and use the plan
      // ID in your client-side code.
        plan: '...',
      quantity: 1
    }],
    success_url: '...',
    cancel_url: '...',
  });
  return error.message;
}
```
I am following these docs https://stripe.com/docs/payments/checkout/subscriptions/starting

**Comment by paulasjes-stripe** [comment]
Hi there. It looks like you perhaps are calling Stripe.js functions before it has been completely loaded onto the page.

Since this has nothing to do with stripe-node I'm going to close this. If the above doesn't fix your issue, then you should reach out to Stripe support here: https://support.stripe.com/contact
