### ISSUE TITLE
Feature Request: Update usage on invoice.created

### ISSUE THREAD

**Issue by pcmaffey** [stripe/stripe-node#725]
For a metered pricing plan, rather than running a daily cron to createUsageRecords for every customer, I'm listening for the invoice.created event triggered at the end of a billing cycle and updating the invoice with metered usage.

Unfortunately,  I can't add a usage record because ` ERROR: Cannot create the usage record with this timestamp because timestamps must be after the subscription's last invoice period (or current period start time)`. So I have to manually create a new line item instead of using the pricing plan.

It would be great if usage records created during the draft period of an invoice could be added to that billing cycle. I'm sure would save you guys tons of posts to createUsageRecord route.

**Comment by remi-stripe** [comment]
@pcmaffey Github issues should be limited to bugs with the stripe-node library itself. Here, the feature request is about the API itself.

I've flagged it internally but I'd recommend that you reach out to our support team to report the feature request so that they can track it and keep you updated. You can reach them here: https://support.stripe.com/contact

**Comment by adamsoffer** [comment]
@pcmaffey I'm running into the same issue. Did you end up finding a workaround?

**Comment by pcmaffey** [comment]
@adamsoffer Not remembering the exact implementation details, but I ended up not using the metered plan, and instead just created a new line item on a subscription plan. Unfortunately, the subscription plan bills at the beginning of the cycle, not the end, so every new subscription had 1 empty invoice to start and every invoice was using the period for the previous invoice.

Definitely a hack, but it seemed like the best workaround with the situation I was dealing with. Not sure why stripe's api is so opinionated about this.

**Comment by adamsoffer** [comment]
Yeah I ended up doing the same but used a free monthly metered price instead of a regular free monthly subscription. This allowed me to close a billing period immediately whenever a user changed plans avoiding the issue you describe. Would be nice if Stripe introduced a webhook right *before* an invoice gets created so I don't have to have a needless free item in the invoice.

**Comment by parweennargis** [comment]
They're using a slightly different timestamp here. You must divide it by 1000.

use: Math.ceil(Date.now() / 1000)
