### ISSUE TITLE
Documentation: how to verify events in express app which already has other body parser middleware

### ISSUE THREAD

**Issue by r3wt** [stripe/stripe-node#734]
The problem is that `bodyParser.raw()` will conflict with all other middleware like `bodyParser.json()`. The solution is to use `bodyParser.json()` and use the verify function to grab the rawBuffer and save it as an request property:
```js

//the below middleware is a workaround so we can get both `rawBody` and our normal `body`. Stripe webhooks need the rawBody
app.use(bodyParser.json({verify: (req, res, buf, encoding)=> {
    if (buf && buf.length) {
        req.rawBody = buf.toString(encoding || 'utf8');
    }
}, type: 'application/json' })); // for parsing application/json

```

then user can use `req.rawBody` to construct the event like this:"

```js
stripe.webhooks.constructEvent(req.rawBody, req.headers['stripe-signature'], config.stripe.webhookSecret);
```

This is the only way to have the raw body and the json body at the same time in one express application, while your docs do not show any warnings at all about this problem. The reason is that `bodyParser.raw()` and `bodyParser.json()` conflict with each other and one will not run if the other has already ran, so the first middleware wins.

**Comment by remi-stripe** [comment]
@r3wt Thanks for the feedback. Express and other Node.js frameworks have definitely been finicky with this in general. We've had many separate issues reported over the years because their framework was parsing the data in various ways and requiring custom configuration to get to the raw body.

I'll flag your feedback internally though I do think that this gets into really specific territory about the framework and something that is more on the developer(s) to adapt to their own environment in that case. But I'll see if we can call this out in the docs more prominently!
