### ISSUE TITLE
Create invoice without pending invoice items

### ISSUE THREAD

**Issue by seblemeur** [stripe/stripe-node#747]
Hey team, is it possible to add this feature :
Create a new invoice without pending invoice items. For now we need to delete all pending invoice items from the customer before creating the new invoice items and creating the invoice.

No updates since this issue ? https://github.com/stripe/stripe-node/issues/518

Thx

**Comment by remi-stripe** [comment]
@seblemeur Thanks for reaching up. It's unfortunately not something we are working on at the moment but we're definitely aware that this is something we need to improve. Hopefully something we can tackle this year.

Going to close this out as github issues should be limited to bugs with the library and this is more a feature request in the API. Don't hesitate to raise this with our support team: https://support.stripe.com/contact

**Comment by seblemeur** [comment]
Ok thx, is it a good practice to :
- get pending invoice items

**Comment by remi-stripe** [comment]
Yes, no other way today.

**Comment by Matsa59** [comment]
@remi-stripe this sounds like really bad workaround. What happen if you have multiple processes that need to create multiple invoice for the same customer ? In our case, we want the customer to be able to have a basket for his items, but he could offer a gift as a separate flow that should not appear in his basket.

Using your workaround, we expose our system to failure because for a short period of time, the customer will not have any invoiceitem. Worse, he could have "extra" invoiceitem in his invoice.

We definitively need to be able to create empty invoices. 

What @simonaudet explains could be a good solution to fix your "backward compatibility issue" (https://github.com/stripe/stripe-node/issues/518)

I can't believe you keep have this issue for 2 years :/

**Comment by remi-stripe** [comment]
@Matsa59 You're not wrong, it has some risks/rough edges. We do want to fix this, but it's not as easy as it appears to be from the outside and it's not that common of an issue either. But it's on our roadmap in the future!
