### ISSUE TITLE
Please add connect examples in React contect

### ISSUE THREAD

**Issue by bionicles** [stripe/stripe-node#755]
I'd like to put Connect on a react app but there's no example. The only example is for a swift app

Would it please be possible to add a usage example of stripe-node to make a stripe connect app?

Then it would be much easier to develop web platform marketplace type things...

**Comment by remi-stripe** [comment]
@bionicles Thanks for reporting this. `stripe-node` is the library used server-side to make API requests in Node.js. The examples you want are specific to React itself for the client-side library. It's definitely something we're aware of and are working on to improve the state of the library and the docs as discussed in https://github.com/stripe/react-stripe-elements/issues/451

I'm going to close the issue here but we're working on improvements!
