### ISSUE TITLE
Typescript: missing "include" from list operations

### ISSUE THREAD

**Issue by Bene-Graham** [stripe/stripe-node#779]
Node Version: 12.13.1
Stripe-Node Version: 8.7.0

I am in the process of updating to the latest version and coming from the definitely typed version I was able to set the include property. The type def with the latest version is missing this.

```typescript
stripe.invoices.list({
    customer: "",
    limit: 10,
    include: ["total_count"], // << Type error
    starting_after = ""
});
```

**Comment by remi-stripe** [comment]
@Bene-Graham The `include` and `total_count` features have been actively deprecated for over 5 years now. While those work, we really discourage anyone from using those. We won't add those to the Typescript definitions because of it. We're also planning to drop support for those parameters, potentially this year, though we will reach out to all users to warn them.

**Comment by Bene-Graham** [comment]
Oh, well that is good to know

Thank You.
