### ISSUE TITLE
stripe.accountlink.create

### ISSUE THREAD

**Issue by Bohica1** [stripe/stripe-node#782]
Node version: v10.16.0
Stripe version: ^latest (8.7.0)

stripe.accountLinks.create is an invalid method
stripe.accountLink.create is an invalid method

After speaking with support this was the guidance.

"from taking a look at your most recent message, it seems you may be calling the endpoint "stripe.accountLinks.create". It seems there may be a slight error in our documentation for PHP and Python here, which instead should read as ' stripe.AccountLink.create '. 

So rather than the plural form 'AccountLinks', it would need to be the singular 'AccountLink'. 
I hope this helps clear things up, but if you have any trouble, do reach right back out."

Unfortunately it isn't accurate. 

As per the documentation stripe.accountLinks.create
https://stripe.com/docs/api/account_links/object?lang=node

In any case neither work. We get an error of the create account is not a defined method. This is after updating the package to the latest and using API version 2019-12-03.

I have resorted to axios requests to keep going as the updates are due by Feb 20th.

**Comment by cjavilla-stripe** [comment]
Hey @Bohica1 

I just tested this and you should be able to make the request using the following:

```
(async () => {
  try {
    const accountLink = await stripe.accountLinks.create({
      account: 'acct_1G0bZZJeGtdrR5oD',
      failure_url: 'https://example.com/failure',
      success_url: 'https://example.com/success',
      type: 'custom_account_verification',
    })
    console.log(accountLink);
  } catch(e) {
    console.log(e);
  }
})();
```

In case it's helpful, there are Stripe engineers available to chat during most business hours in the #stripe channel on Freenode (https://webchat.freenode.net/?channel=#stripe). If that fails, please let us know on support.stripe.com/contact or IRC the error you're getting. Thanks!

**Comment by adminsfmeal** [comment]
Hi @cjavilla-stripe 

When I used your code to make the request, an error return:
"You must have a client application set in order to make this request.".

I have attached my request log in stripe dashboard:

ID: req_atLCs0gF97o2sq
Time: 2/9/20, 3:42:10 AM
Method: POST
URL: /v1/account_links
Status: 400
IP address: 104.238.63.95
Version: 2019-12-03 (latest)
Source: Stripe/v1 NodeBindings/8.14.0
Related: account — acct_17IRrjH35MjVlUlP

`{
  "account": "acct_17IRrjH35MjVlUlP",
  "failure_url": "http://localhost:1337/host/apply",
  "success_url": "http://localhost:1337/host/setup/success",
  "type": "custom_account_verification",
  "collect": "eventually_due"
}`

My Node version: v12.13.1
My Stripe-Node version: 8.14
