### ISSUE TITLE
Error calling stripe.accountLinks.create

### ISSUE THREAD

**Issue by adminsfmeal** [stripe/stripe-node#798]
Hi @cjavilla-stripe 

When I used your code to make the request, an error return:
"You must have a client application set in order to make this request.".

I have attached my request log in stripe dashboard:

ID: req_atLCs0gF97o2sq
Time: 2/9/20, 3:42:10 AM
Method: POST
URL: /v1/account_links
Status: 400
IP address: 104.238.63.95
Version: 2019-12-03 (latest)
Source: Stripe/v1 NodeBindings/8.14.0
Related: account — acct_17IRrjH35MjVlUlP

`{
  "account": "acct_17IRrjH35MjVlUlP",
  "failure_url": "http://localhost:1337/host/apply",
  "success_url": "http://localhost:1337/host/setup/success",
  "type": "custom_account_verification",
  "collect": "eventually_due"
}`

My Node version: v12.13.1
My Stripe-Node version: 8.14

_Originally posted by @adminsfmeal in https://github.com/stripe/stripe-node/issues/782#issuecomment-583841448_

**Comment by remi-stripe** [comment]
@adminsfmeal You're passing the wrong account id in the `account` parameter. This is is your own account when it's supposed to be the id of a connected Express or Custom account instead.

I'm going to close this issue out since this is not an issue with the library. Don't hesitate to contact our support team directly if you're still stuck after that: https://support.stripe.com/contact
