### ISSUE TITLE
Unit tests with stripe-v3

### ISSUE THREAD

**Issue by fgisslen** [stripe/stripe-node#814]
Hi,
probably I am asking at the wrong place but I can't find any good answers on the web.
I use Stripe in my Angular 9 app. I use this package and import stripe-v3 in index.html.

Everything works fine but not in my unit tests. Then it says ReferenceError: Stripe is not defined .

Does anyone know what the problem is? 

Thanks

**Comment by remi-stripe** [comment]
@fgisslen This message seems to indicate that Stripe.js is not properly loaded when you run your unit tests. I'd recommend that you reach out to our support team instead and provide a lot more details about your setup: how you load Stripe.js, how you run your tests, what your code looks like, etc. You can contact them here: https://support.stripe.com/contact

Going to close the issue here as issues should be limited to bug with the stripe-node library which you are not using.
