### ISSUE TITLE
Missing consume_applied_balance param

### ISSUE THREAD

**Issue by lpellegr** [stripe/stripe-node#815]
The documentation states the following:

> Customer balances applied to all invoices are now debited or credited back to the customer when voided. Earlier, applied customer balances were not returned back to the customer and were consumed.
> 
> To achieve this behavior in earlier API versions:
> - Set consume_applied_balance to false when voiding invoices in /v1/invoices/:id/void.
> - Set invoice_customer_balance_settings[consume_applied_balance_on_void] to false in /v1/subscriptions create or update to force this behavior for Invoices voided by a Subscription.
> - Set subscription_data[invoice_customer_balance_settings][consume_applied_balance_on_void] to false in /v1/checkout/sessions create to force this behavior for Invoices voided by Subscriptions created with Checkout.

Using Stripe NodeJS library version `8.20.0` and API version `2019-12-03`, it seems there is no `consume_applied_balance` definition in the TypeScript params definition for `stripe.invoices.voidInvoice`. The same seems to apply for `stripe.subscriptions.create` and `stripe.subscriptions.update`.

**Comment by remi-stripe** [comment]
@lpellegr Our Typescript definitions always represent the latest API version. The parameter `consume_applied_balance_on_void` does not exist on the latest API version since it's the default behaviour already. It was added to enable the new behaviour on older API versions and only exist on those. You can still pass this parameter if you are using an older API version in your code, it's just not part of the definitions.
