### ISSUE TITLE
stripe.accounts.listPersons is not a function

### ISSUE THREAD

**Issue by frabbidgdean** [stripe/stripe-node#818]
Stripe npm version: 8.19.0
node version: 10.16.3
Stripe API version: 2019-12-03
Issue:

Upon invoking stripe.accounts.listPersons function, I am receiving the following error:

  stripe.accounts.listPersons is not a function
I am able to use other functions listed under stripe.accounts (e.g. retrieve, update, etc.)
https://stripe.com/docs/api/persons/list?lang=node

**Comment by remi-stripe** [comment]
@frabbidgdean Are you sure you're on the latest version of stripe-node? `listPersons` is defined here in the code: https://github.com/stripe/stripe-node/blob/master/lib/resources/Accounts.js#L113

**Comment by frabbidgdean** [comment]
> @frabbidgdean Are you sure you're on the latest version of stripe-node? `listPersons` is defined here in the code: https://github.com/stripe/stripe-node/blob/master/lib/resources/Accounts.js#L113

Yes, I am. I am invoking the function as listed in the example.

stripe.accounts.listPersons(
  'acct_103Gfh2D4cn0FjNI',
  {limit: 3},
  function(err, persons) {
    // asynchronously called
  }
);

**Comment by frabbidgdean** [comment]
![image](https://user-images.githubusercontent.com/42651002/75199890-4c66ac80-5732-11ea-99e1-2fef7d698021.png)
This is an example from my VS Code debugger

**Comment by remi-stripe** [comment]
@frabbidgdean Would you be able to provide a bit more context around how you're using this? That method was added in 2018 as you can see [here](https://github.com/stripe/stripe-node/pull/507/files#diff-c5979c86332c8dd8762e61b72b2ca8d8R115) so it hasn't even been renamed or changed.

Are you maybe using third-party Typescript definitions such as the ones from DefinitelyTyped instead of the official ones in the library?

**Comment by frabbidgdean** [comment]
Following is the snippet where I am getting this error


`
'use strict';

const stripe = require('stripe')('stripe_key');
stripe.setApiVersion('2019-12-03');

const Business = module.exports;


Business.getPersons = function (stripe_account_id) {
    return stripe.accounts.listPersons(
        stripe_account_id,
        { limit: 3 }
      );
};
`

**Comment by frabbidgdean** [comment]
My project is not using TypeScript.

**Comment by remi-stripe** [comment]
@frabbidgdean I'm fairly certain the issue is due to having the wrong version of stripe-node installed. Based on your screenshot, you have `retrieve` as an API method and nothing else. I do think you need to double check the exact version of the library that is installed. Maybe your `package.json` is pinned to an older version of the library and you missed this?

**Comment by frabbidgdean** [comment]
@remi-stripe the issue was with my docker image caching the older version of the package. I apologize for your inconvenience and thank you very much for your assistance.

**Comment by remi-stripe** [comment]
No worries at all, I'm glad you were able to resolve this quickly :)
