### ISSUE TITLE
Documentation for Stripe Payment and Order API

### ISSUE THREAD

**Issue by nejurgis** [stripe/stripe-node#846]
This is regarding clarity of documentation and could probably be seen as a feature request (to make docs more clear)

Dear All, I'm making an e-commerce web app with Gatsby and am confused what is the most modern way to attach SKU's / items that are being purchased to the Payment Intent?  I couldn't find info about this in the documentation and its a bit confusing overall after SEPA changes and Order API deprecation, since there's no clear guide on how to do it. 

I'm using card payments and Ideal with stripe-react-elements and my node lambda functions that I wrote can be found here:
[Creating Order](https://github.com/nejurgis/inNout/blob/master/src/functions/orderCreate.js)
[Payment Intent](https://github.com/nejurgis/inNout/blob/master/src/functions/paymentIntent.js)

**Comment by paulasjes-stripe** [comment]
For questions about the API instead of stripe-node specifically you're better off contacting Stripe support at https://support.stripe.com/contact.

In your case, you'd retrieve the price from the SKU you're interested in, multiply that by the amount of items being purchased and then pass that value in as the amount for your PaymentIntent. There is currently no way to link a SKU to a PaymentIntent automatically.
