### ISSUE TITLE
Type Definitions for Stripe Constructor requires a StripeConfig

### ISSUE THREAD

**Issue by benbotto** [stripe/stripe-node#863]
Node version 10.17.0
Typescript version 3.4.4
Stripe version 8.39.0

The type definitions for the `Stripe` constructor require a `StripeConfig` object to be passed in.  This contradicts the documentation (https://www.npmjs.com/package/stripe#usage-with-typescript).  In the JavaScript code (`lib/stripe.js`), the `Stripe` constructor defaults the `config` parameter to `{}`, but that's not an option in TypeScript because the `StripeConfig` interface has require properties (`apiVersion`).

Please update the documentation to show a minimum `StripeConfig` object, and/or update the type definitions to have an appropriate default.

**Comment by cjavilla-stripe** [comment]
Hey benbotto!

Sorry for any confusion. The docs do not show the config being required, because it's optional when using vanilla javascript. When using typescript it's required because the types are pinned to a specific API version. 

https://github.com/stripe/stripe-node#usage-with-typescript

**Comment by benbotto** [comment]
Thanks @cjavilla-stripe.  I guess what I'm wondering is why it's required when using TS since it all boils down to JS anyway.  Further, why require a parameter that can only have one value?  It's not like an end-user can configure the api version: `StripeConfig` has `apiVersion`'s type as `LatestApiVersion`, and that's hard-coded to '2020-03-02'.

https://github.com/stripe/stripe-node/blob/master/types/lib.d.ts#L24
https://github.com/stripe/stripe-node/blob/master/types/lib.d.ts#L8

Doesn't that seem a bit superfluous?

**Comment by cjavilla-stripe** [comment]
Ah good question. It's required for TS because we only ship one version of the types per library and those types are pinned to the specific API version, so we want to ensure that the API version used on the Stripe account is the same API version used with the library and warn you if it's not set. By specifying the API version explicitly in the options object, that forces the API version for requests to match that version resulting in responses that match the types for that API version. If no API version is specified then the default API version on your Stripe account is used, which could be different from latest and the responses will stop matching the types. 

For instance, say you're on latest API version today and you setup your entire system without passing the options block with the API version set. Then in 3 years when you decide you want to update your Stripe accounts API version to access some new functionality, but you forget that your Stripe-node version is dependent on your Stripe account API version, by upgrading the version on Stripe you'd break your stripe-node integration without knowing. Alternatively, by requiring that you set the API version explicitly if you were to upgrade your default API version on Stripe later, because it's explicitly specified in the options block when initializing stripe-node, you don't break your stripe-node integration by changing the default on your Stripe account.

**Comment by benbotto** [comment]
Got it, that makes sense.  Thanks @cjavilla-stripe.
