### ISSUE TITLE
@types/stripe: 7.13.22 - stripe.charges.update() - amount field missing #43944

### ISSUE THREAD

**Issue by alan345** [stripe/stripe-node#869]
- [X] I tried using the "@types/stripe": "^7.13.22" package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wjohnsto and @CodeAnimal 
Definitions by: William Johnston <https://github.com/wjohnsto>, Peter Harris <https://github.com/codeanimal/>

We are using now Typescript and Stripe library: "@types/stripe": "^7.13.22",

Unfortunately, this exceptional call:

```
const charge = await stripe.charges.update(
  'ch_1CmMk3IyNTgGDVfzqgWGCQr5',
  {
    amount: 2500,
  }
);
```

Described here: https://stripe.com/docs/issuing/testing#increasing-the-amount-of-an-authorization is not correctly typed.

The type error thrown is: Argument of type '{ amount: number; }' is not assignable to parameter of type 'ChargeUpdateParams'.

It is because this hook: Update a charge (https://stripe.com/docs/api/charges/update) doesn't have the value "amount" in the type 'ChargeUpdateParams'.
Thanks!

**Comment by richardm-stripe** [comment]
Hi @alan345, thank you for the report!

A couple notes: this is the repo for the Stripe library itself, not the community-maintained DefinitelyTyped bindings that are found in `@types/stripe`. As of this year we now provide [Typescript definitions directly in this library](https://github.com/stripe/stripe-node#usage-with-typescript]), which did not use to be the case. We recommend you switch away from the DefinitelyTyped definitions to the official ones provided with the library, which you should be able to do by uninstalling the `@types/stripe` and changing your import definition to
`import Stripe from 'stripe'` (instead of `* as Stripe`). Unlike the community-maintained definitions, the definitions we ship alongside the library are generated from our API spec and so we can more easily make sure they are complete and current.

Second, the reason that the type definition for `ChargeUpdateParams` lacks the `amount` field is because this field isn't part of the standard Stripe API. There are some fields tied to features that are only enabled for users in certain circumstances, and this is one of those. (One way to tell -- https://stripe.com/docs/issuing/testing#increasing-the-amount-of-an-authorization won't be visible if you log out of Stripe).

We recommend you work around the type error by adding a `//@ts-ignore` above the offending line.

**Comment by kamil-stripe** [comment]
I hope @richardm-stripe's suggestion works for you. Please reopen the issue in case of additional questions.
