### ISSUE TITLE
Error: No such token: src_restOfStringHere error on WeChat as sources on stripe

### ISSUE THREAD

**Issue by hayderameen** [stripe/stripe-node#889]
I am trying to use WeChat payment sources on Stripe. The client side is working fine, QR Code is generated and I can scan it on phone to go to payment page.

However, when I try to charge it on node.js backend (after source becomes chargeable), I get this error that no such token.

I can confirm that test keys on both ends are correct. Moreover, I am using correct source here in this code as mentioned in documentation.

const charge = await stripe.charges.create({
  amount: 1099,
  currency: 'usd',
  source: 'src_18eYalAHEMiOZZp1l9ZTjSU0',
});

All the values are correct. I verified them from client side and what is received on server side. 

However, this issue is persistent. Any help would be appreciated since I cannot find any support for WeChat Payment Stripe source anywhere else. 

Thanks in advance.

**Comment by remi-stripe** [comment]
@hayderameen Github issues should be limited to  bugs with the stripe-node library itself. Since this is a question about the API itself, I would recommend talking to our support team instead: https://support.stripe.com/contact

This error though is definitely due to using the wrong Source id (src_123) or the wrong API keys somewhere. That Source id is not a WeChat Source and is instead an ACH Source for example. You should triple check the Source id you are working with and that the API key client-side and server-side are associated with the correct account. Otherwise our support team will be able to help you debug this.
