### ISSUE TITLE
Feature request: Support Terminal Hardware Orders

### ISSUE THREAD

**Issue by kyleabens** [stripe/stripe-node#914]
https://stripe.com/docs/api/terminal/hardware_orders/create?lang=node

<img width="1097" alt="Screen Shot 2020-06-05 at 4 39 43 PM" src="https://user-images.githubusercontent.com/25699262/83921012-75440800-a74b-11ea-8f5a-ee1b6e5e09fb.png">

**Comment by remi-stripe** [comment]
@kyleabens That API is in private beta at the moment and unfortunately we don't support private/secret betas in our client libraries today. The reason is that the API changes a lot during betas and we only want stable and core features to be in our official libraries.

There's an easier way to make HTTP requests through stripe-node on new endpoints though and it would look something like this:

```
const resource = Stripe.StripeResource.extend({
  request: Stripe.StripeResource.method({
    method: 'POST',
    path: 'terminal/hardware_orders',
  })
});

const order = await new resource(stripe).request({
  // parameters
});
```

**Comment by kyleabens** [comment]
@remi-stripe Got it, thanks for the quick response!

**Comment by kyleabens** [comment]
@remi-stripe When I try adding your code snippet I get `Property 'StripeResource' does not exist on type 'typeof Stripe'.`  I'm using version 8.60.0.

**Comment by remi-stripe** [comment]
@kyleabens sorry for the confusion on that one. You have to initialize the library a bit differently so it'd look like this:

```
const Stripe = require('stripe');
const stripe = Stripe('sk_test_123');

const resource = Stripe.StripeResource.extend({
  request: Stripe.StripeResource.method({
    method: 'POST',
    path: 'terminal/hardware_orders',
  })
});

const order = await new resource(stripe).request({
  // parameters
});
```
