### ISSUE TITLE
Charge error on re-submit new/same card after canceling 3D Secure popup

### ISSUE THREAD

**Issue by redbaron76** [stripe/stripe-node#934]
Node versione: 10.18.0
Card form: react-stripe-js
Stripe.js latest version

As in the title, I'm facing a ```Error: A source must be attached to a customer to be used as a `payment_method`.``` on re-submitting both the same or a new credit card after the cancelation or failure trigger of the 3D Secure popup.
The transaction succeeds only if I re-submit the same token saved from the previous attempt.

The first charge object is like this:
```
{ amount: 1000,
currency: 'EUR',
payment_method: 'card_1GzH5PKiD2TNK7HzMpJBAjvW',
confirm: true,
confirmation_method: 'manual',
transfer_data: { amount: 970, destination: 'acct_1GqqlgBVGx1Z2PjR' }
```
and it works if I correctly authorize it.

But if I cancel the authorization or I trigger the failure option and I use a new card, I try to charge this new charge object:
```
{ amount: 1000,
currency: 'EUR',
payment_method: 'card_1GzH6fKiD2TNK7HzxMeMxMa1',
confirm: true,
confirmation_method: 'manual',
transfer_data: { amount: 970, destination: 'acct_1GqqlgBVGx1Z2PjR' },
```
and this fails with:
```
raw:
 { message: 'A source must be attached to a customer to be used as a `payment_method`.',
param: 'payment_method',
type: 'invalid_request_error',
headers:
{ server: 'nginx',
date: 'Mon, 29 Jun 2020 07:08:46 GMT',
'content-type': 'application/json',
'content-length': '180',
connection: 'keep-alive',
'access-control-allow-credentials': 'true',
'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
'access-control-allow-origin': '*',
'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
'access-control-max-age': '300',
'cache-control': 'no-cache, no-store',
request-id': 'req_MwF7L0a0Mzw0CZ',
'stripe-version': '2017-02-14',
'strict-transport-security': 'max-age=31556926; includeSubDomains; preload' },
statusCode: 400,
equestId: 'req_MwF7L0a0Mzw0CZ' }
```

Am I doing something wrong or is there something related with the library?
Did not find any solution with it at this at the moment.

Thanks

**Comment by remi-stripe** [comment]
@redbaron76 Thanks for reaching out. Github issues should be limited to bug with the library itself. Here, it seems that the issue is due to the way you use the API which you should discuss with our support team instead: https://support.stripe.com/contact

Looking into this on our end though it seems to just be due to creating a Token (tok_123) and then trying to confirm the PaymentIntent with the card id inside the token. This won't work. You have to attach the card to the customer first because you're using a legacy API (Token and Card) instead of the more recent one (PaymentMethod).

If you have any follow up questions though our support team will be able to help.
