### ISSUE TITLE
Feature Request: Made webhook events expandable

### ISSUE THREAD

**Issue by johnnyperdomo** [stripe/stripe-node#939]
Currently, I believe there is no way to expand incoming webhook events.

Sometimes I may need more information on the customer or the invoice, without having to make an extra api call to get more information on the customer.

One idea I had of how to implement this: when configuring 'webhook events to send' from the dashboard, maybe having a dropdown with optional expandable parameters. Or, adding a small text-box to the specific 'event to send', where developers can type their own 'expand' request parameters.

**Comment by remi-stripe** [comment]
@johnnyperdomo Thanks for the feedback! At the moment, we don't plan to support something like this and we recommend fetching the resource you need when you receive the event instead so that you can expand what you need at that point.

I'm going to close this out because it's not really a feature request for the library itself and more one for the Dashboard/API so I'd recommend also flagging to our support team: https://support.stripe.com/contact
