### ISSUE TITLE
 5 vulnerabilities in npm package of stripe on node js

### ISSUE THREAD

**Issue by itsaareez1** [stripe/stripe-node#942]
NPM 6.4.1
Node v10.15.3

5 vulnerable packages while installing stripe on node js

**Comment by richardm-stripe** [comment]
@itsaareez1 can you share how you determined this? For example, I did `npm install stripe` in an empty project and received
```shell
$ npm install stripe
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN new@1.0.0 No description
npm WARN new@1.0.0 No repository field.

+ stripe@8.68.0
added 3 packages from 50 contributors and audited 3 packages in 0.583s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by itsaareez1** [comment]
I received the following result. I have installed on existing project.   
    
    $ npm install stripe
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})     

    + stripe@8.68.0
    updated 1 package and audited 307 packages in 5.766s
    found 5 low severity vulnerabilities
      run `npm audit fix` to fix them, or `npm audit` for details

**Comment by richardm-stripe** [comment]
When npm outputs
> found 5 low severity vulnerabilities
the meaning is that there are 5 low severity vulnerabilities throughout your entire project's dependency tree, not just in the dependencies of the package you just installed. Since installing `stripe` in an empty project displayed no vulnerabilities, I think the source of this message must be a different npm module that you are using. You can run `npm audit` to confirm this.

Closing for now, as I don't think there is any action to take.
