### ISSUE TITLE
Issue with Stripe.Subscription Documentation Example

### ISSUE THREAD

**Issue by XavierGeerinck** [stripe/stripe-node#979]
Hi There,

When utilizing the Node.JS Typescript bindings, when I copy/paste the Subscription object example from "https://stripe.com/docs/api/subscriptions/object" it seems that Typescript is returning an error.

```
    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/stripe/stripe.mocks.ts:89:11 - error TS2741: Property 'trial_period_days' is missing in type '{ aggregate_usage: null; interval: "month"; interval_count: number; usage_type: "licensed"; }' but required in type 'Recurring'.

    89           "recurring": {
                 ~~~~~~~~~~~

      node_modules/stripe/types/2020-03-02/Prices.d.ts:123:9
        123         trial_period_days: number | null;
                    ~~~~~~~~~~~~~~~~~
        'trial_period_days' is declared here.
      node_modules/stripe/types/2020-03-02/Prices.d.ts:68:7
        68       recurring: Price.Recurring | null;
                 ~~~~~~~~~
        The expected type comes from property 'recurring' which is declared here on type 'Price'
```

Now when I add this one (even though it shows as optional, I keep getting further errors. Main issues:

1. "trial_period_days" seems to be required, even though the binding allows null. Now adding `null` gives a further error (see 2.)
2. "plan" seems to be missing (defined in SubscriptionItems.d.ts - line 45)

Am I doing something wrong here?

**Comment by paulasjes-stripe** [comment]
Hi there, looks like `trial_period_days` should perhaps be optional rather than required. We're looking into it!

**Comment by XavierGeerinck** [comment]
Awesome! And what about Plan? :)

**Comment by remi-stripe** [comment]
@XavierGeerinck The thing is that `plan` is guaranteed to be returned in the API but we have actively undocumented it from our API reference since it is being replace by the `Price` API instead. This means that our Typescript signatures are correct, as they mirror what the API really returns but our API reference and the example fixture is forward looking for when we ship an API version that removes support for Plan. We want to discourage new developers to look at Plan by mistake.

Similarly `trial_period_days` in `recurring` can only be set on a Price if it was created in the past as a Plan. So as we hide Plan more often, the recurring hash itself will lose `trial_period_days` too.

I'm sorry for the confusion on this one. I don't think we considered this situation when tweaking the fixtures in the API reference where you would load from it to try and map to the Typescript definition. This might be confusing though we haven't seen other reports yet, but hopefully it clarifies what the issue is and what you should expect.

If you are building a new integration though, ignore the Plan API and any plan parameter or property entirely and just focus on the Price API instead.

**Comment by Minishlink** [comment]
@remi-stripe Hi, I wanted to upgrade node-stripe today and saw this problem. How would you access the subscription's `priceId` with the new typings? Is it safe to rely on `items`?

**Comment by remi-stripe** [comment]
@Minishlink Yes relying on `items` is the right approach since a Subscription can have more than 1 price at a time!

**Comment by Minishlink** [comment]
@remi-stripe Ok, thanks!
